# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CTC.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys
from PyQt5.QtWidgets import  QFileDialog
from CTC.train import Train
from CTC.ctc import CTC
from PyQt5 import QtCore, QtGui, QtWidgets
from CTC.test_ui import testUI
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *

class mainUI(QMainWindow):

    def __init__(self, ctc: CTC):
        super().__init__()
        self.CTC = ctc
        self.trackSymbol = {0: "🟢", 1: "🟡", 2: "🔴"}
        self.station = {}
        self.setupUi()
        self.show()


    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(950, 950)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(130, 0, 700, 580))
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 0, 1000, 1000))
        self.groupBox.setObjectName("mainUI")
        self.tab_Mode = QtWidgets.QTabWidget(self.groupBox)
        self.tab_Mode.setGeometry(QtCore.QRect(100, 600, 721, 261))
        self.tab_Mode.setObjectName("tab_Mode")
        self.Automatic = QtWidgets.QWidget()
        self.Automatic.setObjectName("Automatic")
        self.label = QtWidgets.QLabel(self.Automatic)
        self.label.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label.setObjectName("label")
        self.s_label = QtWidgets.QLabel(self.Automatic)
        self.s_label.setGeometry(QtCore.QRect(45, 3, 140, 16))
        self.s_label.setObjectName("s_label")
        self.schedule = QtWidgets.QToolButton(self.Automatic)
        self.schedule.setGeometry(QtCore.QRect(10, 0, 30, 20))
        self.schedule.setObjectName("schedule")
        self.label_2 = QtWidgets.QLabel(self.Automatic)
        self.label_2.setGeometry(QtCore.QRect(320, 30, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Automatic)
        self.label_3.setGeometry(QtCore.QRect(520, 30, 81, 16))
        self.label_3.setObjectName("label_3")
        self.autoTable = QtWidgets.QTableWidget(self.Automatic)
        self.autoTable.setGeometry(QtCore.QRect(10, 50, 475, 175))
        self.autoTable.setObjectName("autoTable")
        self.autoTable.setColumnCount(5)
        self.autoTable.setRowCount(0)
        self.autoTable.setColumnWidth(0, 90)
        self.autoTable.setColumnWidth(1, 100)
        self.autoTable.setColumnWidth(2, 100)
        self.autoTable.setColumnWidth(3, 100)
        self.autoTable.setColumnWidth(3, 75)

        item = QtWidgets.QTableWidgetItem()
        self.autoTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.autoTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.autoTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.autoTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.autoTable.setHorizontalHeaderItem(4, item)
        # self.auto2table = QtWidgets.QTableWidget(self.Automatic)
        # self.auto2table.setGeometry(QtCore.QRect(320, 50, 191, 151))
        # self.auto2table.setObjectName("auto2table")
        # self.auto2table.setColumnCount(2)
        # self.auto2table.setRowCount(0)
        # self.auto2table.setColumnWidth(0, 90)
        # self.auto2table.setColumnWidth(1, 90)

        # item = QtWidgets.QTableWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignCenter|QtCore.Qt.AlignVCenter)
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # item.setFont(font)
        # self.auto2table.setHorizontalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignCenter|QtCore.Qt.AlignVCenter)
        # self.auto2table.setHorizontalHeaderItem(1, item)
        self.auto3table = QtWidgets.QTableWidget(self.Automatic)
        self.auto3table.setGeometry(QtCore.QRect(520, 50, 191, 175))
        self.auto3table.setObjectName("auto3table")
        self.auto3table.setColumnCount(2)
        self.auto3table.setRowCount(0)
        self.auto3table.setColumnWidth(0, 90)
        self.auto3table.setColumnWidth(1, 90)
        item = QtWidgets.QTableWidgetItem()
        self.auto3table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.auto3table.setHorizontalHeaderItem(1, item)
        self.tab_Mode.addTab(self.Automatic, "")
        self.Manual = QtWidgets.QWidget()
        self.Manual.setObjectName("Manual")
        self.timeSelect = QtWidgets.QTimeEdit(self.Manual)
        self.timeSelect.setGeometry(QtCore.QRect(600, 90, 118, 22))
        self.timeSelect.setObjectName("timeSelect")
        self.confirmButton = QtWidgets.QPushButton(self.Manual)
        self.confirmButton.setGeometry(QtCore.QRect(600, 180, 75, 24))
        self.confirmButton.setObjectName("confirmButton")
        self.trainSelect = QtWidgets.QComboBox(self.Manual)
        self.trainSelect.setGeometry(QtCore.QRect(420, 90, 151, 31))
        self.trainSelect.setObjectName("trainSelect")
        self.trainSelect.addItem("")
        self.label_4 = QtWidgets.QLabel(self.Manual)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 181, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Manual)
        self.label_5.setGeometry(QtCore.QRect(420, 70, 181, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Manual)
        self.label_6.setGeometry(QtCore.QRect(420, 160, 181, 16))
        self.label_6.setObjectName("label_6")
        self.stationSelect = QtWidgets.QComboBox(self.Manual)
        self.stationSelect.setGeometry(QtCore.QRect(420, 180, 151, 31))
        self.stationSelect.setObjectName("stationSelect")
        self.stationSelect.addItem("1")
        self.stationSelect.addItem("2")
        self.label_7 = QtWidgets.QLabel(self.Manual)
        self.label_7.setGeometry(QtCore.QRect(600, 70, 121, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Manual)
        self.label_8.setGeometry(QtCore.QRect(600, 160, 101, 16))
        self.label_8.setObjectName("label_8")
        self.label_22 = QtWidgets.QLabel(self.Manual)
        self.label_22.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_22.setObjectName("label_22")
        self.lineSelect1 = QtWidgets.QComboBox(self.Manual)
        self.lineSelect1.setGeometry(QtCore.QRect(10, 30, 151, 31))
        self.lineSelect1.setObjectName("lineSelect")
        self.lineSelect1.addItem("Blue")
        self.lineSelect1.addItem("Green")
        self.lineSelect1.addItem("Red")
        self.manualTable = QtWidgets.QTableWidget(self.Manual)
        self.manualTable.setGeometry(QtCore.QRect(10, 90, 390, 120))
        self.manualTable.setObjectName("manualTable")
        self.manualTable.setColumnCount(4)
        self.manualTable.setRowCount(0)
        self.manualTable.setColumnWidth(0, 80)
        self.manualTable.setColumnWidth(1, 90)
        self.manualTable.setColumnWidth(2, 90)
        self.manualTable.setColumnWidth(3, 120)
        item = QtWidgets.QTableWidgetItem()
        self.manualTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.manualTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.manualTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.manualTable.setHorizontalHeaderItem(3, item)
        self.tab_Mode.addTab(self.Manual, "")
        self.Maintenance = QtWidgets.QWidget()
        self.Maintenance.setObjectName("Maintenance")
        self.maintenanceTable = QtWidgets.QTableWidget(self.Maintenance)
        self.maintenanceTable.setGeometry(QtCore.QRect(10, 50, 401, 171))
        self.maintenanceTable.setObjectName("maintenanceTable")
        self.maintenanceTable.setColumnCount(4)
        self.maintenanceTable.setRowCount(0)
        self.maintenanceTable.setColumnWidth(0, 80)
        self.maintenanceTable.setColumnWidth(1, 110)
        self.maintenanceTable.setColumnWidth(2, 100)
        self.maintenanceTable.setColumnWidth(3, 100)
        self.confirmButton2 = QtWidgets.QPushButton(self.Maintenance)
        self.confirmButton2.setGeometry(QtCore.QRect(610, 125, 75, 24))
        self.confirmButton2.setObjectName("confirmButton2")
        self.label_13 = QtWidgets.QLabel(self.Maintenance)
        self.label_13.setGeometry(QtCore.QRect(610, 105, 181, 16))
        self.label_13.setObjectName("label_13")
        item = QtWidgets.QTableWidgetItem()
        self.maintenanceTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.maintenanceTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.maintenanceTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.maintenanceTable.setHorizontalHeaderItem(3, item)
        self.label_10 = QtWidgets.QLabel(self.Maintenance)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 181, 16))
        self.label_10.setObjectName("label_10")
        self.lineSelect = QtWidgets.QComboBox(self.Maintenance)
        self.lineSelect.setGeometry(QtCore.QRect(440, 40, 151, 31))
        self.lineSelect.setObjectName("lineSelect")
        self.lineSelect.addItem("Blue")
        self.lineSelect.addItem("Green")
        self.lineSelect.addItem("Red")

        self.label_11 = QtWidgets.QLabel(self.Maintenance)
        self.label_11.setGeometry(QtCore.QRect(440, 20, 181, 16))
        self.label_11.setObjectName("label_11")
        self.trackSelect = QtWidgets.QComboBox(self.Maintenance)
        self.trackSelect.setGeometry(QtCore.QRect(440, 120, 151, 31))
        self.trackSelect.setObjectName("trackSelect")

        self.label_12 = QtWidgets.QLabel(self.Maintenance)
        self.label_12.setGeometry(QtCore.QRect(440, 100, 181, 16))
        self.label_12.setObjectName("label_12")

        self.radioButton = QtWidgets.QRadioButton(self.Maintenance)
        self.radioButton.setGeometry(QtCore.QRect(610, 50, 95, 20))
        self.radioButton.setObjectName("radioButton")

        self.label_sw = QtWidgets.QLabel(self.Maintenance)
        self.label_sw.setGeometry(QtCore.QRect(440, 170, 181, 16))
        self.label_sw.setObjectName("label_sw")

        self.label_ps = QtWidgets.QLabel(self.Maintenance)
        self.label_ps.setGeometry(QtCore.QRect(610, 170, 181, 16))
        self.label_ps.setObjectName("label_ps")

        self.setSwitch = QtWidgets.QComboBox(self.Maintenance)
        self.setSwitch.setGeometry(QtCore.QRect(440, 190, 100, 31))
        self.setSwitch.setObjectName("setSwitch")

        self.setPosition = QtWidgets.QComboBox(self.Maintenance)
        self.setPosition.setGeometry(QtCore.QRect(610, 190, 95, 31))
        self.setPosition.setObjectName("setPosition")

        self.tab_Mode.addTab(self.Maintenance, "")



        # self.setPosition = QtWidgets.QLabel(self.Maintenance)
        # self.setPosition.setGeometry(QtCore.QRect(440, 140, 181, 16))
        # self.setPosition.setObjectName("setPosition")

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(200, 10, 700, 565))
        self.label_9.setObjectName("label_9")
        self.time_label = QtWidgets.QLabel(self.groupBox)
        self.time_label.setGeometry(QtCore.QRect(370, 860, 151, 21))
        self.time_label.setObjectName("time_label")
        self.pause = QtWidgets.QPushButton(self.groupBox)
        self.pause.setGeometry(QtCore.QRect(368, 879, 75, 24))
        self.pause.setObjectName("pause")
        self.play = QtWidgets.QPushButton(self.groupBox)
        self.play.setGeometry(QtCore.QRect(448, 879, 75, 24))
        self.play.setObjectName("play")
        self.sim_speed = QtWidgets.QSpinBox(self.groupBox)
        self.sim_speed.setGeometry(QtCore.QRect(540, 879, 42, 22))
        self.sim_speed.setObjectName("sim_speed")
        self.sim_speed.setMinimum(1)
        self.sim_speed.setMaximum(20)
        self.sim_speed.setMaximum(20)
        self.throughput = QtWidgets.QLabel(self.groupBox)
        self.throughput.setGeometry(QtCore.QRect(100, 860, 250, 16))
        self.throughput.setObjectName("throughput")
        self.throughput2 = QtWidgets.QLabel(self.groupBox)
        self.throughput2.setGeometry(QtCore.QRect(100, 880, 250, 16))
        self.throughput2.setObjectName("throughput2")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(540, 860, 91, 20))
        self.label_19.setObjectName("label_19")

        # self.stationCCount = QtWidgets.QLCDNumber(self.centralwidget)
        # self.stationCCount.setGeometry(QtCore.QRect(710, 250, 50, 23))
        # self.stationCCount.setObjectName("stationCCount")
        # self.stationCCount.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        # self.stationBCount = QtWidgets.QLCDNumber(self.centralwidget)
        # self.stationBCount.setGeometry(QtCore.QRect(660, 90, 50, 23))
        # self.stationBCount.setObjectName("stationBCount")
        # self.stationBCount.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.statusBLine1 = QtWidgets.QLabel(self.centralwidget)
        self.statusBLine1.setGeometry(QtCore.QRect(266, 146, 30, 16))
        self.statusBLine1.setObjectName("statusBLine1")
        self.statusBLine2 = QtWidgets.QLabel(self.centralwidget)
        self.statusBLine2.setGeometry(QtCore.QRect(310, 146, 31, 16))
        self.statusBLine2.setObjectName("statusBLine2")
        self.statusBLine3 = QtWidgets.QLabel(self.centralwidget)
        self.statusBLine3.setGeometry(QtCore.QRect(360, 140, 31, 30))
        self.statusBLine3.setObjectName("statusBLine3")
        self.statusBLine4 = QtWidgets.QLabel(self.centralwidget)
        self.statusBLine4.setGeometry(QtCore.QRect(408, 150, 30, 10))
        self.statusBLine4.setObjectName("statusBLine4")
        self.statusBLine5 = QtWidgets.QLabel(self.centralwidget)
        self.statusBLine5.setGeometry(QtCore.QRect(458, 150, 30, 10))
        self.statusBLine5.setObjectName("statusBLine5")
        self.statusBLine9 = QtWidgets.QLabel(self.centralwidget)
        self.statusBLine9.setGeometry(QtCore.QRect(621, 89, 30, 10))
        self.statusBLine9.setObjectName("statusBLine9")
        self.statusBLine8 = QtWidgets.QLabel(self.centralwidget)
        self.statusBLine8.setGeometry(QtCore.QRect(587, 102, 30, 10))
        self.statusBLine8.setObjectName("statusBLine8")
        self.statusBLine7 = QtWidgets.QLabel(self.centralwidget)
        self.statusBLine7.setGeometry(QtCore.QRect(550, 120, 30, 10))
        self.statusBLine7.setObjectName("statusBLine7")
        self.statusBLine6 = QtWidgets.QLabel(self.centralwidget)
        self.statusBLine6.setGeometry(QtCore.QRect(512, 132, 30, 10))
        self.statusBLine6.setObjectName("statusBLine6")
        self.statusBLine11 = QtWidgets.QLabel(self.centralwidget)
        self.statusBLine11.setGeometry(QtCore.QRect(501, 162, 30, 10))
        self.statusBLine11.setObjectName("statusBLine11")
        self.statusBLine12 = QtWidgets.QLabel(self.centralwidget)
        self.statusBLine12.setGeometry(QtCore.QRect(551, 181, 30, 10))
        self.statusBLine12.setObjectName("statusBLine12")
        self.statusBLine13 = QtWidgets.QLabel(self.centralwidget)
        self.statusBLine13.setGeometry(QtCore.QRect(608, 199, 30, 10))
        self.statusBLine13.setObjectName("statusBLine13")
        self.statusBLine14 = QtWidgets.QLabel(self.centralwidget)
        self.statusBLine14.setGeometry(QtCore.QRect(660, 213, 30, 10))
        self.statusBLine14.setObjectName("statusBLine14")
        self.groupBox.raise_()
        self.graphicsView.raise_()
        self.label_9.raise_()
        # self.stationCCount.raise_()
        # self.stationBCount.raise_()
        self.statusBLine1.raise_()
        self.statusBLine2.raise_()
        self.statusBLine3.raise_()
        self.statusBLine4.raise_()
        self.statusBLine5.raise_()
        self.statusBLine9.raise_()
        self.statusBLine8.raise_()
        self.statusBLine7.raise_()
        self.statusBLine6.raise_()
        self.statusBLine11.raise_()
        self.statusBLine12.raise_()
        self.statusBLine13.raise_()
        self.statusBLine14.raise_()
        self.setCentralWidget(self.centralwidget)
        self.K = QtWidgets.QLabel(self.centralwidget)
        self.K.setGeometry(QtCore.QRect(696, 378, 49, 16))
        self.K.setObjectName("K")
        self.L = QtWidgets.QLabel(self.centralwidget)
        self.L.setGeometry(QtCore.QRect(669, 529, 49, 16))
        self.L.setObjectName("L")
        self.M = QtWidgets.QLabel(self.centralwidget)
        self.M.setGeometry(QtCore.QRect(524, 540, 49, 16))
        self.M.setObjectName("M")
        self.N = QtWidgets.QLabel(self.centralwidget)
        self.N.setGeometry(QtCore.QRect(380, 540, 49, 16))
        self.N.setObjectName("N")
        self.P = QtWidgets.QLabel(self.centralwidget)
        self.P.setGeometry(QtCore.QRect(211, 499, 49, 16))
        self.P.setObjectName("P")
        self.Q = QtWidgets.QLabel(self.centralwidget)
        self.Q.setGeometry(QtCore.QRect(322, 512, 49, 16))
        self.Q.setObjectName("Q")
        self.R = QtWidgets.QLabel(self.centralwidget)
        self.R.setGeometry(QtCore.QRect(437, 515, 49, 16))
        self.R.setObjectName("R")
        self.S = QtWidgets.QLabel(self.centralwidget)
        self.S.setGeometry(QtCore.QRect(505, 491, 49, 16))
        self.S.setObjectName("S")
        self.T = QtWidgets.QLabel(self.centralwidget)
        self.T.setGeometry(QtCore.QRect(572, 471, 49, 16))
        self.T.setObjectName("T")
        self.U = QtWidgets.QLabel(self.centralwidget)
        self.U.setGeometry(QtCore.QRect(580, 397, 49, 16))
        self.U.setObjectName("U")
        self.V = QtWidgets.QLabel(self.centralwidget)
        self.V.setGeometry(QtCore.QRect(566, 310, 49, 16))
        self.V.setObjectName("V")
        self.W = QtWidgets.QLabel(self.centralwidget)
        self.W.setGeometry(QtCore.QRect(500, 292, 49, 16))
        self.W.setObjectName("W")
        self.X = QtWidgets.QLabel(self.centralwidget)
        self.X.setGeometry(QtCore.QRect(246, 274, 49, 16))
        self.X.setObjectName("X")
        self.Y = QtWidgets.QLabel(self.centralwidget)
        self.Y.setGeometry(QtCore.QRect(225, 213, 49, 16))
        self.Y.setObjectName("Y")
        self.Z = QtWidgets.QLabel(self.centralwidget)
        self.Z.setGeometry(QtCore.QRect(241, 154, 49, 16))
        self.Z.setObjectName("Z")
        self.D = QtWidgets.QLabel(self.centralwidget)
        self.D.setGeometry(QtCore.QRect(380, 40, 49, 16))
        self.D.setObjectName("D")
        self.B = QtWidgets.QLabel(self.centralwidget)
        self.B.setGeometry(QtCore.QRect(471, 101, 49, 16))
        self.B.setObjectName("B")
        self.A = QtWidgets.QLabel(self.centralwidget)
        self.A.setGeometry(QtCore.QRect(420, 60, 49, 16))
        self.A.setObjectName("A")
        self.C = QtWidgets.QLabel(self.centralwidget)
        self.C.setGeometry(QtCore.QRect(611, 37, 49, 16))
        self.C.setObjectName("C")
        self.I = QtWidgets.QLabel(self.centralwidget)
        self.I.setGeometry(QtCore.QRect(510, 215, 49, 16))
        self.I.setObjectName("I")
        self.J = QtWidgets.QLabel(self.centralwidget)
        self.J.setGeometry(QtCore.QRect(640, 240, 49, 16))
        self.J.setObjectName("J")
        self.F = QtWidgets.QLabel(self.centralwidget)
        self.F.setGeometry(QtCore.QRect(330, 110, 49, 16))
        self.F.setObjectName("F")
        self.E = QtWidgets.QLabel(self.centralwidget)
        self.E.setGeometry(QtCore.QRect(320, 50, 49, 16))
        self.E.setObjectName("E")
        self.H = QtWidgets.QLabel(self.centralwidget)
        self.H.setGeometry(QtCore.QRect(330, 210, 49, 16))
        self.H.setObjectName("H")
        self.G = QtWidgets.QLabel(self.centralwidget)
        self.G.setGeometry(QtCore.QRect(326, 164, 49, 16))
        self.G.setObjectName("G")
        self.O = QtWidgets.QLabel(self.centralwidget)
        self.O.setGeometry(QtCore.QRect(293, 566, 49, 16))
        self.O.setObjectName("O")
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 26))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMain.menuAction())
        self.retranslateUi()
        self.tab_Mode.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)
        #print("HERE1")
        self.handler()
        #print("HERE3")

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.tab_Mode.setToolTip(_translate("MainWindow", "<html><head/><body><p>Manual</p><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Train Info"))
        self.s_label.setText(_translate("MainWindow", "Upload Auto Schedule"))
        self.label_2.setText(_translate("MainWindow", ""))
        self.label_3.setText(_translate("MainWindow", "Track Info"))
        item = self.autoTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Train ID"))
        item = self.autoTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Current Dest."))
        item = self.autoTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Arrival Time"))
        item = self.autoTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Location"))
        item = self.autoTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Line"))

        # item = self.auto2table.horizontalHeaderItem(0)
        # item.setText(_translate("MainWindow", "Station ID"))
        # item = self.auto2table.horizontalHeaderItem(1)
        # item.setText(_translate("MainWindow", "# Waiting"))
        item = self.auto3table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Block #"))
        item = self.auto3table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        self.tab_Mode.setTabText(self.tab_Mode.indexOf(self.Automatic), _translate("MainWindow", "Automatic"))
        self.confirmButton.setText(_translate("MainWindow", "Dispatch"))
        self.trainSelect.setItemText(0, _translate("MainWindow", "New Train"))
        self.label_4.setText(_translate("MainWindow", "Selection Info"))
        self.label_5.setText(_translate("MainWindow", "Train Select"))
        self.label_6.setText(_translate("MainWindow", "Station Select(Destination)"))
        self.stationSelect.setItemText(0, _translate("MainWindow", "1"))
        self.stationSelect.setItemText(1, _translate("MainWindow", "2"))
        self.label_7.setText(_translate("MainWindow", "Arrival Time Select"))
        self.label_8.setText(_translate("MainWindow", "Confirm Changes"))
        item = self.manualTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Train ID"))
        item = self.manualTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Current Dest"))
        item = self.manualTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Dest"))
        item = self.manualTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Arrival Time"))
        self.tab_Mode.setTabText(self.tab_Mode.indexOf(self.Manual), _translate("MainWindow", "Manual"))
        self.confirmButton2.setText(_translate("MainWindow", "Confirm"))
        item = self.maintenanceTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Line"))
        item = self.maintenanceTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Block #"))
        item = self.maintenanceTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        item = self.maintenanceTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Status"))
        self.label_10.setText(_translate("MainWindow", "Selection Info"))
        self.label_22.setText(_translate("MainWindow", "Line Select"))

        self.lineSelect.setItemText(0, _translate("MainWindow", "Blue"))
        self.lineSelect.setItemText(1, _translate("MainWindow", "Green"))
        self.label_11.setText(_translate("MainWindow", "Line Select"))
        #for i in range(14):
           # self.trackSelect.setItemText(i, _translate("MainWindow", str(i+1)))
        # if (self.lineSelect.currentText() == "Blue"):
        #     self.trackSelect.clear()
        #     for i in range(1, 17):
        #         self.trackSelect.addItem(str(i))
                #self.trackSelect.setItemText(i, _translate("MainWindow", str(i)))


        self.label_12.setText(_translate("MainWindow", "Block Select"))
        self.label_sw.setText(_translate("MainWindow", "Switch Select"))
        self.radioButton.setText(_translate("MainWindow", "Open/Close"))
        self.label_ps.setText(_translate("MainWindow", "Position Select"))

        self.label_13.setText(_translate("MainWindow", "Confirm Changes"))
        self.tab_Mode.setTabText(self.tab_Mode.indexOf(self.Maintenance), _translate("MainWindow", "Maintenance"))

        self.time_label.setText(_translate("MainWindow", "Time"))
        self.pause.setText(_translate("MainWindow", "Pause"))
        self.play.setText(_translate("MainWindow", "Start"))
        self.label_19.setText(_translate("MainWindow", "Sim Speed"))
        # self.throughput.setText(_translate("MainWindow", "(Blue Line) Passengers/hr: "))
        # self.throughput2.setText(_translate("MainWindow", "(Red Line) Passengers/hr: "))

        self.time_label.setText(_translate("MainWindow", "Time"))

        self.setSwitch.addItem(str(13))
        self.setSwitch.addItem(str(28))
        self.setSwitch.addItem(str(57))
        self.setSwitch.addItem(str(62))
        self.setSwitch.addItem(str(77))
        self.setSwitch.addItem(str(85))

        self.setPosition.addItem("Left")
        self.setPosition.addItem("Right")
        #self.label_9.setPixmap(QtGui.QPixmap("C:/Users/zdego/OneDrive/Desktop/1140/Hub/train_system/CTC/blueLIne.png"))

        dir_path = os.path.dirname(os.path.realpath(__file__))
        self.label_9.setPixmap(QtGui.QPixmap(dir_path+"\green_red_line.png"))
        #self.label_9.setPixmap(QtGui.QPixmap("C:/Users/zdego/OneDrive/Desktop/1140/Hub/train_system/CTC/red_green_line_smaller.png"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        # self.statusBLine1.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.statusBLine2.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.statusBLine3.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.statusBLine4.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.statusBLine5.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.statusBLine9.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.statusBLine8.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.statusBLine7.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.statusBLine6.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.statusBLine11.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.statusBLine12.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.statusBLine13.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.statusBLine14.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.K.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.L.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.M.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.N.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.P.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.Q.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.R.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.S.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.T.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.U.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.V.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.W.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.X.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.Y.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.Z.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.D.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.B.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.A.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.C.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.I.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.J.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.F.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.E.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.H.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.G.setText(_translate("MainWindow", self.trackSymbol[0]))
        # self.O.setText(_translate("MainWindow", self.trackSymbol[0]))
        self.allStatus = [self.statusBLine1, self.statusBLine2, self.statusBLine3, self.statusBLine4, self.statusBLine5, self.statusBLine6, self.statusBLine7, self.statusBLine8, self.statusBLine9, self.statusBLine9, self.statusBLine11, self.statusBLine12, self.statusBLine13, self.statusBLine14]
        self.allStatus2 = [self.A, self.B, self.C, self.D, self.E, self.F, self.G, self.H, self.I, self.J, self.K, self.L, self.M, self.N, self.O, self.P, self.Q, self.R, self.S, self.T, self.U, self.V, self.W, self.X, self.Y, self.Z]
        self.lineSelect1.activated.connect(self.updateAutoBox)
        self.stationSelect.activated.connect(self.updateManualTable)
        self.trainSelect.currentIndexChanged.connect(self.updateManualTable)
        self.timeSelect.timeChanged.connect(self.updateManualTable)

        self.lineSelect.activated.connect(self.updateCombo2)
        self.trackSelect.currentIndexChanged.connect(self.updateMaintenanceTable)
        self.radioButton.clicked.connect(self.updateMaintenanceTable)

        self.confirmButton.clicked.connect(self.updateTrain)
        self.confirmButton2.clicked.connect(self.updateTrack)
        self.play.clicked.connect(self.start_time)
        self.pause.clicked.connect(self.stop_time)
        self.schedule.pressed.connect(self.readFile)

        self.setPosition.activated.connect(self.updateSwitch)

    def readFile(self):
        file, check = QFileDialog.getOpenFileName(None, "QFileDialog.getOpenFileName()", "", "CSV Files (*.csv)")
        #stationList = []
        if check:
            f = open(file, "r", encoding ='utf-8-sig')
            for train in f:
                stationList = []
                train = train.strip('\n')
                info = train.split(',')
                line = info[0]
                for i in range(1, 21):
                    if len(info[i]) > 0:
                        stationList.append(info[i])
                arrival_time = info[21].replace('"','')
                self.CTC.addTrain2(stationList, arrival_time, line)



    def updateCombo2(self):
        self.trackSelect.clear()
        self.setSwitch.clear()
        _translate = QtCore.QCoreApplication.translate

        if (self.lineSelect.currentText() == "Blue"):
            for i in range(1, 17):
                self.trackSelect.addItem(str(i))
                #self.trackSelect.setItemText(i, _translate("MainWindow", str(i)))
        elif (self.lineSelect.currentText() == "Green"):
            for i in range(1, 151):
                self.trackSelect.addItem(str(i))
            self.setSwitch.addItem(str(13))
            self.setSwitch.addItem(str(28))
            self.setSwitch.addItem(str(57))
            self.setSwitch.addItem(str(62))
            self.setSwitch.addItem(str(77))
            self.setSwitch.addItem(str(85))

        elif (self.lineSelect.currentText() == "Red"):
            for i in range(1, 77):
                self.trackSelect.addItem(str(i))
            self.setSwitch.addItem(str(16))
            self.setSwitch.addItem(str(52))
                # self.trackSelect.setItemText(i, _translate("MainWindow", str(i)))
    def updateAutoBox(self):
        self.stationSelect.clear()
        if (self.lineSelect1.currentText() == "Blue"):
            self.stationSelect.addItem(str(1))
            self.stationSelect.addItem(str(2))
        elif (self.lineSelect1.currentText() == "Green"):
            self.stationSelect.addItem("2 Pioneer")
            self.stationSelect.addItem("9 Edgebrook")
            self.stationSelect.addItem("16 Station")
            self.stationSelect.addItem("22 Whited")
            self.stationSelect.addItem("31 South Bank")
            self.stationSelect.addItem("39 Central")
            self.stationSelect.addItem("48 Inglewood")
            self.stationSelect.addItem("56 Overbrook")
            self.stationSelect.addItem("65 Glenbury")
            self.stationSelect.addItem("73 Dormont")
            self.stationSelect.addItem("77 Mt. Lebanon")
            self.stationSelect.addItem("88 Poplar")
            self.stationSelect.addItem("96 Castle Shannon")
            self.stationSelect.addItem("105 Dormont")
            self.stationSelect.addItem("114 Glenbury")
            self.stationSelect.addItem("123 Overbrook")
            self.stationSelect.addItem("132 Inglewood")
            self.stationSelect.addItem("141 Central")
        elif (self.lineSelect1.currentText() == "Red"):
            self.stationSelect.addItem("7 Shadyside")
            self.stationSelect.addItem("16 Herron Ave")
            self.stationSelect.addItem("21 Swissville")
            self.stationSelect.addItem("25 Pennstation")
            self.stationSelect.addItem("35 Steel Plaza")
            self.stationSelect.addItem("45 First Ave")
            self.stationSelect.addItem("48 Station Square")
            self.stationSelect.addItem("60 South Hills")


    def stop_time(self):
        self.CTC.time_toggle = 0

    def start_time(self):
        self.CTC.time_toggle = 1

    def updateTrack(self):
        index = int(self.trackSelect.currentText()) -1
        line = self.lineSelect.currentText()
        value = self.radioButton.isChecked()
        if line == "Green":
            l = 2
        elif line == "Red":
            l = 1
        else:
            l = 0

        self.CTC.editTrack(l, index, value)
        #track[int(self.trackSelect.currentText()) -1] = self.radioButton.isChecked()

        self.updateAutoTable()
        self.updateTrackStatus()

    def updateCombo(self):
        for i in range(self.trainSelect.count()-1, len(self.CTC.getTrainList())):
            if self.CTC.getTrainList()[i].location != -1:
                self.trainSelect.addItem(str(i+1))

    def updateTrain(self):
        train = self.trainSelect.currentText()
        line = self.lineSelect1.currentText()
        destination = self.stationSelect.currentText()

        destination = destination.split(" ")[0]
        time = self.timeSelect.time().toString()

        if(train == "New Train"):

            self.CTC.addTrain(int(destination), str(time), str(line))
            #New = Train()
            #New.setTrainID(len(self.officeList)+1)
            #New.setDestination(destination)
            #New.setArrival_time(str(time))
            #self.officeList.append(New)
            self.trainSelect.addItem(str(len(self.CTC.getTrainList())))
            self.updateAutoTable()
        else:
            id = int(self.trainSelect.currentText()) - 1
            self.CTC.editTrain(id, destination, str(time))
            #self.officeList[int(self.trainSelect.currentText())-1].destination = self.stationSelect.currentText()
            #self.officeList[int(self.trainSelect.currentText())-1].arrival_time = str(self.timeSelect.time().toString())
            self.updateManualTable()


    def updateMaintenanceTable(self):
        if self.lineSelect.currentText() == "Green":
            line = 2
        elif self.lineSelect.currentText() == "Red":
            line = 1
        else:
            line = 0

        track = self.CTC.getTrackList(line)
        self.maintenanceTable.setRowCount(1)
        self.maintenanceTable.setItem(0, 0, QtWidgets.QTableWidgetItem(str(self.lineSelect.currentText())))
        self.maintenanceTable.setItem(0, 1, QtWidgets.QTableWidgetItem(str(self.trackSelect.currentIndex()+1)))


        if track[int(self.trackSelect.currentIndex())] != 2:
            self.maintenanceTable.setItem(0, 2, QtWidgets.QTableWidgetItem(str("Open")))
        else:
            self.maintenanceTable.setItem(0, 2, QtWidgets.QTableWidgetItem(str("Closed")))
        if self.radioButton.isChecked():
            self.maintenanceTable.setItem(0, 3, QtWidgets.QTableWidgetItem(str("Open")))
        else:
            self.maintenanceTable.setItem(0, 3, QtWidgets.QTableWidgetItem(str("Closed")))



    def updateAutoTable(self):
        trainList = self.CTC.getTrainList()
        self.autoTable.setRowCount(len(trainList))
        for i, train in enumerate(trainList):
            if train.location != -1:
                self.autoTable.setItem(i, 0, QtWidgets.QTableWidgetItem(str(train.train_id)))
                self.autoTable.setItem(i, 1, QtWidgets.QTableWidgetItem(str(train.destination)))
                self.autoTable.setItem(i, 2, QtWidgets.QTableWidgetItem(train.arrival_time))
                self.autoTable.setItem(i, 3, QtWidgets.QTableWidgetItem(str(train.location)))
                self.autoTable.setItem(i, 4, QtWidgets.QTableWidgetItem(str(train.line)))


        station = self.CTC.getStationList()
        # self.auto2table.setRowCount(len(station))
        # for i in range(len(station)):
        #     self.auto2table.setItem(i, 0, QtWidgets.QTableWidgetItem(str(i+1)))
        #     self.auto2table.setItem(i, 1, QtWidgets.QTableWidgetItem(str(station[i])))


        index = []
        n = int(self.lineSelect.currentIndex())

        if n == 1:
            num = 2
        elif n == 2:
            num = 1
        else:
            num = 0
        track = self.CTC.getTrackList(num)
        count = track.count(2)
        self.auto3table.setRowCount(count)
        for x in range(len(track)):
            if track[x] == 2:
                index.append(x+1)
        for x in range(count):
            self.auto3table.setItem(x, 0, QtWidgets.QTableWidgetItem(str(index[x])))
            self.auto3table.setItem(x, 1, QtWidgets.QTableWidgetItem("Closed"))

        station = self.CTC.getStationList()
        # self.stationBCount.display(str(station[0]))
        # self.stationCCount.display(str(station[1]))


    def updateManualTable(self):
        trainList = self.CTC.getTrainList()
        self.manualTable.setRowCount(1)
        self.manualTable.setItem(0, 0, QtWidgets.QTableWidgetItem(self.trainSelect.currentText()))
        if(self.trainSelect.currentText() != "New Train"):
            self.manualTable.setItem(0, 1, QtWidgets.QTableWidgetItem(trainList[int(self.trainSelect.currentText())-1].destination))
        else:
            self.manualTable.setItem(0, 1, QtWidgets.QTableWidgetItem("NA"))
        self.manualTable.setItem(0, 2, QtWidgets.QTableWidgetItem(self.stationSelect.currentText()))
        self.manualTable.setItem(0, 3, QtWidgets.QTableWidgetItem(self.timeSelect.time().toString()))

        self.autoTable.setRowCount(len(trainList))
        for i in range(len(trainList)):
            if trainList[i].completed != 1:
                self.autoTable.setItem(i, 0, QtWidgets.QTableWidgetItem(str(trainList[i].train_id)))
                self.autoTable.setItem(i, 1, QtWidgets.QTableWidgetItem(trainList[i].destination))
                self.autoTable.setItem(i, 2, QtWidgets.QTableWidgetItem(trainList[i].arrival_time))

    def updateSwitch(self):
        switchnum = self.setSwitch.currentText()
        position = self.setPosition.currentText()
        line = self.lineSelect.currentText()
        self.CTC.setSwitch(position, int(switchnum), line)
    def updateThroughput(self):
        _translate = QtCore.QCoreApplication.translate
        self.CTC.getThroughput(2)
        self.throughput.setText(_translate("MainWindow", "(Green Line) Passengers/hr: " + self.CTC.getThroughput(1)))
        self.throughput2.setText(_translate("MainWindow", "(Red Line) Passengers/hr: " + self.CTC.getThroughput(2)))

    def updateTrackStatus(self):
        trainList = self.CTC.getTrainList()
        trackList = self.CTC.getTrackList(1)
        _translate = QtCore.QCoreApplication.translate

        # if 2 in trackList[63:69]:
        #     self.allStatus2[10].setText(_translate("Form", self.trackSymbol[2]))
        # elif 1 in trackList[63:69]:
        #     self.allStatus2[10].setText(_translate("Form", self.trackSymbol[1]))
        # else:
        #     self.allStatus2[10].setText(_translate("Form", self.trackSymbol[0]))
        #
        # if 2 in trackList[69:74]:
        #     self.allStatus2[11].setText(_translate("Form", self.trackSymbol[2]))
        # elif 1 in trackList[69:64]:
        #     self.allStatus2[11].setText(_translate("Form", self.trackSymbol[1]))
        # else:
        #     self.allStatus2[11].setText(_translate("Form", self.trackSymbol[0]))
        #
        # if 2 in trackList[74:77]:
        #     self.allStatus2[11].setText(_translate("Form", self.trackSymbol[2]))
        # elif 1 in trackList[74:77]:
        #     self.allStatus2[11].setText(_translate("Form", self.trackSymbol[1]))
        # else:
        #     self.allStatus2[11].setText(_translate("Form", self.trackSymbol[0]))
        #
        # if 2 in trackList[69:74]:
        #     self.allStatus2[11].setText(_translate("Form", self.trackSymbol[2]))
        # elif 1 in trackList[63:69]:
        #     self.allStatus2[11].setText(_translate("Form", self.trackSymbol[1]))
        # else:
        #     self.allStatus2[11].setText(_translate("Form", self.trackSymbol[0]))
        #
        # if 2 in trackList[69:74]:
        #     self.allStatus2[11].setText(_translate("Form", self.trackSymbol[2]))
        # elif 1 in trackList[63:69]:
        #     self.allStatus2[11].setText(_translate("Form", self.trackSymbol[1]))
        # else:
        #     self.allStatus2[11].setText(_translate("Form", self.trackSymbol[0]))



        # for i in range(len(self.allStatus)):
        #     if(i == 9):
        #         continue
        #     elif(i in location):
        #         self.allStatus[i-1].setText(_translate("Form", self.trackSymbol[2]))
        #
        #     else:
        #         self.allStatus[i].setText(_translate("Form", self.trackSymbol[trackList[i]]))


    def updater(self):
        _translate = QtCore.QCoreApplication.translate
        self.time_label.setText(_translate("MainWindow", str(self.CTC.timeformatted())))
        self.CTC.sim_speed = self.sim_speed.value()
        self.updateAutoTable()
        self.updateCombo()
        self.updateTrackStatus()
        self.updateThroughput()
    def handler(self):
        self.timer = QTimer(self)
        self.timer.setInterval(100)
        self.timer.timeout.connect(self.updater)
        self.timer.start()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    ctc = CTC()
    e = testUI(ctc)
    e1 = mainUI(ctc)

    sys.exit(app.exec_())
