import sys
from train_controller.train_controller import TrainController
from signals.train_signals import TrainSignals
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import QRegExpValidator

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EngineerUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)


class DriverUI(QMainWindow):
    def __init__(self, train_controller: TrainController) -> None:
        super().__init__()
        self._train_controller = train_controller
        self._fault_symbols = {False: "✅", True: "❌"}
        self.setupUi()
        self.show()

    def setupUi(self):
        self.setObjectName("Driver UI")
        self.resize(700, 458)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(20, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(80, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(210, 60, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setGeometry(QtCore.QRect(20, 100, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self)
        self.label_7.setGeometry(QtCore.QRect(300, 100, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.speed_slider = QtWidgets.QSlider(self)
        self.speed_slider.setGeometry(QtCore.QRect(20, 130, 311, 22))
        self.speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.speed_slider.setObjectName("speed_slider")
        self.speed_input = QtWidgets.QLineEdit(self)
        self.speed_input.setGeometry(QtCore.QRect(220, 100, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.speed_input.setFont(font)
        self.speed_input.setObjectName("speed_input")
        reg_ex = QRegExp("^[0-9]*$")
        input_validator = QRegExpValidator(reg_ex, self.speed_input)
        self.speed_input.setValidator(input_validator)
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 16, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(315, 150, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self)
        self.label_8.setGeometry(QtCore.QRect(170, 210, 47, 13))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.speed = QtWidgets.QLabel(self)
        self.speed.setGeometry(QtCore.QRect(150, 60, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.speed.setFont(font)
        self.speed.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.speed.setObjectName("speed")
        self.label_10 = QtWidgets.QLabel(self)
        self.label_10.setGeometry(QtCore.QRect(20, 190, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self)
        self.label_11.setGeometry(QtCore.QRect(150, 190, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_11.setFont(font)
        self.label_11.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self)
        self.label_12.setGeometry(QtCore.QRect(200, 190, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self)
        self.label_13.setGeometry(QtCore.QRect(20, 220, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self)
        self.label_14.setGeometry(QtCore.QRect(120, 220, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_14.setFont(font)
        self.label_14.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self)
        self.label_15.setGeometry(QtCore.QRect(180, 220, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self)
        self.label_16.setGeometry(QtCore.QRect(480, 220, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self)
        self.label_17.setGeometry(QtCore.QRect(460, 330, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.left_door_close_btn = QtWidgets.QPushButton(self)
        self.left_door_close_btn.setGeometry(QtCore.QRect(20, 310, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.left_door_close_btn.setFont(font)
        self.left_door_close_btn.setAutoFillBackground(False)
        self.left_door_close_btn.setObjectName("left_door_close_btn")
        self.label_18 = QtWidgets.QLabel(self)
        self.label_18.setGeometry(QtCore.QRect(40, 360, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.lights_off_btn = QtWidgets.QPushButton(self)
        self.lights_off_btn.setGeometry(QtCore.QRect(20, 390, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lights_off_btn.setFont(font)
        self.lights_off_btn.setObjectName("lights_off_btn")
        self.label_19 = QtWidgets.QLabel(self)
        self.label_19.setGeometry(QtCore.QRect(60, 280, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.left_door_open_btn = QtWidgets.QPushButton(self)
        self.left_door_open_btn.setGeometry(QtCore.QRect(110, 310, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.left_door_open_btn.setFont(font)
        self.left_door_open_btn.setObjectName("left_door_open_btn")
        self.lights_on_btn = QtWidgets.QPushButton(self)
        self.lights_on_btn.setGeometry(QtCore.QRect(110, 390, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lights_on_btn.setFont(font)
        self.lights_on_btn.setObjectName("lights_on_btn")
        self.right_door_open_btn = QtWidgets.QPushButton(self)
        self.right_door_open_btn.setGeometry(QtCore.QRect(310, 310, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.right_door_open_btn.setFont(font)
        self.right_door_open_btn.setObjectName("right_door_open_btn")
        self.right_door_close_btn = QtWidgets.QPushButton(self)
        self.right_door_close_btn.setGeometry(QtCore.QRect(220, 310, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.right_door_close_btn.setFont(font)
        self.right_door_close_btn.setObjectName("right_door_close_btn")
        self.label_20 = QtWidgets.QLabel(self)
        self.label_20.setGeometry(QtCore.QRect(250, 280, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.station_label = QtWidgets.QLabel(self)
        self.station_label.setGeometry(QtCore.QRect(420, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.station_label.setFont(font)
        self.station_label.setObjectName("station_label")
        self.label_22 = QtWidgets.QLabel(self)
        self.label_22.setGeometry(QtCore.QRect(435, 40, 246, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_22.setFont(font)
        self.label_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self)
        self.label_23.setGeometry(QtCore.QRect(420, 80, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self)
        self.label_24.setGeometry(QtCore.QRect(420, 120, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self)
        self.label_25.setGeometry(QtCore.QRect(420, 160, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.engine_fault = QtWidgets.QLabel(self)
        self.engine_fault.setGeometry(QtCore.QRect(580, 60, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.engine_fault.setFont(font)
        self.engine_fault.setObjectName("engine_fault")
        self.signal_fault = QtWidgets.QLabel(self)
        self.signal_fault.setGeometry(QtCore.QRect(580, 100, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.signal_fault.setFont(font)
        self.signal_fault.setObjectName("signal_fault")
        self.brake_fault = QtWidgets.QLabel(self)
        self.brake_fault.setGeometry(QtCore.QRect(580, 140, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.brake_fault.setFont(font)
        self.brake_fault.setObjectName("brake_fault")
        self.ebrakeButton = QtWidgets.QPushButton(self)
        self.ebrakeButton.setGeometry(QtCore.QRect(430, 360, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.ebrakeButton.setFont(font)
        self.ebrakeButton.setStyleSheet("background-color:  rgb(255, 0, 0)")
        self.ebrakeButton.setObjectName("ebrakeButton")
        self.serviceBrake_btn = QtWidgets.QPushButton(self)
        self.serviceBrake_btn.setGeometry(QtCore.QRect(430, 250, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.serviceBrake_btn.setFont(font)
        self.serviceBrake_btn.setStyleSheet("")
        self.serviceBrake_btn.setObjectName("serviceBrake_btn")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.ext_lights_on_btn = QtWidgets.QPushButton(self)
        self.ext_lights_on_btn.setGeometry(QtCore.QRect(310, 390, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.ext_lights_on_btn.setFont(font)
        self.ext_lights_on_btn.setObjectName("ext_lights_on_btn")
        self.label_21 = QtWidgets.QLabel(self)
        self.label_21.setGeometry(QtCore.QRect(240, 360, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.ext_lights_off_btn = QtWidgets.QPushButton(self)
        self.ext_lights_off_btn.setGeometry(QtCore.QRect(220, 390, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.ext_lights_off_btn.setFont(font)
        self.ext_lights_off_btn.setObjectName("ext_lights_off_btn")

        self.pushButton.clicked.connect(lambda: self._mode_clicked(False))
        self.pushButton_2.clicked.connect(lambda: self._mode_clicked(True))
        self.lights_off_btn.clicked.connect(
            lambda: self._train_controller.toggle_lights(False)
        )
        self.lights_on_btn.clicked.connect(
            lambda: self._train_controller.toggle_lights(True)
        )

        self.ext_lights_on_btn.clicked.connect(
            lambda: self._train_controller.toggle_ext_lights(True)
        )

        self.ext_lights_off_btn.clicked.connect(
            lambda: self._train_controller.toggle_ext_lights(False)
        )

        self.left_door_open_btn.clicked.connect(
            lambda: self._train_controller.set_doors(left_door=True, door_open=True)
        )
        self.left_door_close_btn.clicked.connect(
            lambda: self._train_controller.set_doors(left_door=True, door_open=False)
        )
        self.right_door_open_btn.clicked.connect(
            lambda: self._train_controller.set_doors(left_door=False, door_open=True)
        )
        self.right_door_close_btn.clicked.connect(
            lambda: self._train_controller.set_doors(left_door=False, door_open=False)
        )

        self.serviceBrake_btn.clicked.connect(
            lambda: self._train_controller.set_service_brake(
                not self._train_controller.get_service_brake()
            )
        )

        self.ebrakeButton.clicked.connect(
            lambda: self._train_controller.set_emergency_brake(
                not self._train_controller.get_emergency_brake()
            )
        )

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        self._handler()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Train Controller"))
        self.label.setText(_translate("Form", "Mode:"))
        self.pushButton.setText(_translate("Form", "Automatic"))
        self.pushButton_2.setText(_translate("Form", "Manual"))
        self.label_2.setText(_translate("Form", "Train's Speed:"))
        self.label_4.setText(_translate("Form", "mph"))
        self.label_6.setText(_translate("Form", "Commanded Speed:"))
        self.label_7.setText(_translate("Form", "mph"))
        self.label_3.setText(_translate("Form", "0"))

        self.label_10.setText(_translate("Form", "Speed Limit:"))
        self.label_12.setText(_translate("Form", "mph"))
        self.label_13.setText(_translate("Form", "Authority:"))
        self.label_15.setText(_translate("Form", "miles"))
        self.label_16.setText(_translate("Form", "Service Brake"))
        self.label_17.setText(_translate("Form", "Emergency Brake"))
        self.left_door_close_btn.setText(_translate("Form", "CLOSE"))
        self.label_18.setText(_translate("Form", "Interior Lights"))
        self.lights_off_btn.setText(_translate("Form", "OFF"))
        self.label_19.setText(_translate("Form", "Left Door"))
        self.left_door_open_btn.setText(_translate("Form", "OPEN"))
        self.lights_on_btn.setText(_translate("Form", "ON"))
        self.right_door_open_btn.setText(_translate("Form", "OPEN"))
        self.right_door_close_btn.setText(_translate("Form", "CLOSE"))
        self.label_20.setText(_translate("Form", "Right Door"))
        self.station_label.setText(_translate("Form", "Next Station:"))
        self.ebrakeButton.setText(_translate("Form", "RELEASE"))
        self.serviceBrake_btn.setText(_translate("Form", "RELEASE"))
        self.ext_lights_on_btn.setText(_translate("Form", "ON"))
        self.label_21.setText(_translate("Form", "Exterior Lights"))
        self.ext_lights_off_btn.setText(_translate("Form", "OFF"))

        self.label_23.setText(_translate("Form", "Train Engine:"))
        self.label_24.setText(_translate("Form", "Signal Pickup:"))
        self.label_25.setText(_translate("Form", "Brakes:"))

        self.speed_input.returnPressed.connect(
            lambda: self.speed_slider.setValue(int(self.speed_input.text()))
            if self.speed_input.text().isdigit()
            else self.speed_slider.setValue(self.speed_slider.value())
        )
        self.speed_slider.valueChanged.connect(
            lambda: self.speed_input.setText(
                _translate("Form", str(self.speed_slider.value()))
            )
        )

    def _update(self):
        _translate = QtCore.QCoreApplication.translate
        self._toggle_mode()
        self._toggle_lights()
        self._toggle_ext_lights()
        self._check_doors()
        self._check_e_brake()
        self._check_service_brake()
        self.label_5.setText(
            _translate("Form", str(round(self._train_controller.get_speed_limit(), 0)))
        )
        self.label_11.setText(
            _translate("Form", str(round(self._train_controller.get_speed_limit(), 0)))
        )
        self.label_14.setText(
            _translate("Form", str(round(self._train_controller.get_authority(), 2)))
        )
        self.speed.setText(
            _translate(
                "Form", str(round(self._train_controller.get_current_speed(), 0))
            )
        )
        self.speed_slider.setMaximum(int(self._train_controller.get_speed_limit()))

        faults = self._train_controller.get_faults()
        self.engine_fault.setText(_translate("Form", self._fault_symbols[faults[0]]))
        self.signal_fault.setText(_translate("Form", self._fault_symbols[faults[1]]))
        self.brake_fault.setText(_translate("Form", self._fault_symbols[faults[2]]))

        self._train_controller.set_setpoint_speed(self.speed_slider.value())
        self.label_22.setText(
            _translate("Form", self._train_controller.get_station_name())
        )

    def _handler(self):
        self.timer = QTimer(self)
        self.timer.setInterval(100)
        self.timer.timeout.connect(self._update)
        self.timer.start()

    @pyqtSlot()
    def _mode_clicked(self, mode: bool):
        if mode:
            self.speed_input.setText(
                str(round(self._train_controller.get_setpoint_speed(), 0))
            )
        else:
            self.speed_input.setText(
                str(round(self._train_controller.get_commanded_speed(), 0))
            )
        self._train_controller.toggle_mode(mode)

    def _toggle_mode(self):
        if self._train_controller.get_mode():
            self.speed_input.setDisabled(False)
            self.speed_slider.setDisabled(False)
            self.lights_off_btn.setDisabled(False)
            self.lights_on_btn.setDisabled(False)
            self.ext_lights_off_btn.setDisabled(False)
            self.ext_lights_on_btn.setDisabled(False)

            if self._train_controller.get_current_speed() > 0:
                self._train_controller.set_doors(True, False)
                self._train_controller.set_doors(False, False)
                self.left_door_open_btn.setDisabled(True)
                self.left_door_close_btn.setDisabled(True)
                self.right_door_open_btn.setDisabled(True)
                self.right_door_close_btn.setDisabled(True)
            else:
                self.left_door_open_btn.setDisabled(False)
                self.left_door_close_btn.setDisabled(False)
                self.right_door_open_btn.setDisabled(False)
                self.right_door_close_btn.setDisabled(False)

            self.pushButton_2.setStyleSheet("background-color : cyan")
            self.pushButton.setStyleSheet("background-color : white")
        else:
            self.speed_input.setDisabled(True)
            self.speed_slider.setDisabled(True)
            self.left_door_open_btn.setDisabled(True)
            self.left_door_close_btn.setDisabled(True)
            self.right_door_open_btn.setDisabled(True)
            self.right_door_close_btn.setDisabled(True)
            self.lights_off_btn.setDisabled(True)
            self.lights_on_btn.setDisabled(True)
            self.ext_lights_off_btn.setDisabled(True)
            self.ext_lights_on_btn.setDisabled(True)

            self.pushButton_2.setStyleSheet("background-color : white")
            self.pushButton.setStyleSheet("background-color : cyan")
            self.speed_input.setText(
                QtCore.QCoreApplication.translate(
                    "Form", str(round(self._train_controller.get_commanded_speed(), 0))
                )
            )

    def _toggle_lights(self):
        if self._train_controller.get_lights():
            self.lights_off_btn.setStyleSheet("background-color : white")
            self.lights_on_btn.setStyleSheet("background-color : cyan")
        else:
            self.lights_off_btn.setStyleSheet("background-color : cyan")
            self.lights_on_btn.setStyleSheet("background-color : white")

    def _toggle_ext_lights(self):
        if self._train_controller.get_ext_lights():
            self.ext_lights_off_btn.setStyleSheet("background-color : white")
            self.ext_lights_on_btn.setStyleSheet("background-color : cyan")
        else:
            self.ext_lights_off_btn.setStyleSheet("background-color : cyan")
            self.ext_lights_on_btn.setStyleSheet("background-color : white")

    def _check_doors(self):
        left_door_open, right_door_open = self._train_controller.get_doors()
        if left_door_open:
            self.left_door_open_btn.setStyleSheet("background-color : cyan")
            self.left_door_close_btn.setStyleSheet("background-color : white")
        else:
            self.left_door_open_btn.setStyleSheet("background-color : white")
            self.left_door_close_btn.setStyleSheet("background-color : cyan")

        if right_door_open:
            self.right_door_open_btn.setStyleSheet("background-color : cyan")
            self.right_door_close_btn.setStyleSheet("background-color : white")
        else:
            self.right_door_open_btn.setStyleSheet("background-color : white")
            self.right_door_close_btn.setStyleSheet("background-color : cyan")

    def _check_service_brake(self):
        if self._train_controller.get_service_brake():
            self.serviceBrake_btn.setText("RELEASE")
        else:
            self.serviceBrake_btn.setText("STOP")

    def _check_e_brake(self):
        if self._train_controller.get_emergency_brake():
            self.ebrakeButton.setText("RELEASE")
        else:
            self.ebrakeButton.setText("STOP")


if __name__ == "__main__":
    app = QApplication(sys.argv)
    e = DriverUI(TrainController(TrainSignals()))
    sys.exit(app.exec_())
