import sys
from train_controller.train_controller import TrainController
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import QRegExpValidator

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EngineerUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)


class EngineerUI(QMainWindow):
    def __init__(self, train_controller: TrainController) -> None:
        super().__init__()
        self._train_controller = train_controller
        self.setupUi()
        self.show()

    def setupUi(self):
        self.setObjectName("EngineerUI")
        self.resize(200, 187)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.setFont(font)

        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(10, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.kp_edit = QtWidgets.QLineEdit(self)
        self.kp_edit.setGeometry(QtCore.QRect(60, 10, 121, 31))
        self.kp_edit.setObjectName("lineEdit")
        font = self.kp_edit.font()  # lineedit current font
        font.setPointSize(13)  # change it's size
        self.kp_edit.setFont(font)
        self.kp_edit.setText(str(self._train_controller.get_gains()[0]))
        reg_ex = QRegExp("^[0-9]\d*(\.\d+)?$")
        input_validator = QRegExpValidator(reg_ex, self.kp_edit)
        self.kp_edit.setValidator(input_validator)

        self.ki_edit = QtWidgets.QLineEdit(self)
        self.ki_edit.setGeometry(QtCore.QRect(60, 50, 121, 31))
        self.ki_edit.setObjectName("lineEdit_2")
        self.ki_edit.setFont(font)
        self.ki_edit.setText(str(self._train_controller.get_gains()[1]))
        input_validator = QRegExpValidator(reg_ex, self.ki_edit)
        self.ki_edit.setValidator(input_validator)

        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(43, 120, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self._submit)
        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, EngineerUI):
        _translate = QtCore.QCoreApplication.translate
        EngineerUI.setWindowTitle(_translate("EngineerUI", "Gains"))
        self.label.setText(_translate("EngineerUI", "KP:"))
        self.label_2.setText(_translate("EngineerUI", "KI:"))
        self.pushButton.setText(_translate("EngineerUI", "SUBMIT"))

    @pyqtSlot()
    def _submit(self):
        if self._train_controller.get_dispatched():
            self.pushButton.setDisabled(True)
            self.kp_edit.setText(str(self._train_controller.get_gains()[0]))
            self.ki_edit.setText(str(self._train_controller.get_gains()[1]))
            return
        kp = (
            self.kp_edit.text()
            if not self.kp_edit.text() == ""
            else self._train_controller.get_gains()[0]
        )
        ki = (
            self.ki_edit.text()
            if not self.ki_edit.text() == ""
            else self._train_controller.get_gains()[1]
        )
        self._train_controller.set_gains(float(kp), float(ki))

        self.kp_edit.setText(str(self._train_controller.get_gains()[0]))
        self.ki_edit.setText(str(self._train_controller.get_gains()[1]))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    e = EngineerUI(TrainController())
    sys.exit(app.exec_())
