import sys
from train_controller.train_controller import TrainController
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import QRegExpValidator
from train_controller.driver_ui import DriverUI
from train_controller.engineer_ui import EngineerUI

# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'EngineerUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)


class TestUI(QMainWindow):
    def __init__(self, train_controller: TrainController) -> None:
        super().__init__()
        self._train_controller = train_controller
        self.setupUi()
        self.show()

    def setupUi(self):
        self.resize(552, 306)
        self.speed_label = QtWidgets.QLabel(self)
        self.speed_label.setGeometry(QtCore.QRect(20, 20, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.speed_label.setFont(font)
        self.speed_label.setObjectName("speed_label")
        self.speed_input = QtWidgets.QLineEdit(self)
        self.speed_input.setGeometry(QtCore.QRect(160, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.speed_input.setFont(font)
        self.speed_input.setObjectName("speed_input")
        self.label_7 = QtWidgets.QLabel(self)
        self.label_7.setGeometry(QtCore.QRect(240, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_17 = QtWidgets.QLabel(self)
        self.label_17.setGeometry(QtCore.QRect(340, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.e_brake_off_btn = QtWidgets.QPushButton(self)
        self.e_brake_off_btn.setGeometry(QtCore.QRect(360, 40, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.e_brake_off_btn.setFont(font)
        self.e_brake_off_btn.setObjectName("e_brake_off_btn")
        self.e_brake_on_btn = QtWidgets.QPushButton(self)
        self.e_brake_on_btn.setGeometry(QtCore.QRect(430, 40, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.e_brake_on_btn.setFont(font)
        self.e_brake_on_btn.setObjectName("e_brake_on_btn")
        self.speed_limit_label = QtWidgets.QLabel(self)
        self.speed_limit_label.setGeometry(QtCore.QRect(20, 130, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.speed_limit_label.setFont(font)
        self.speed_limit_label.setObjectName("speed_limit_label")
        self.speed_limit_input = QtWidgets.QLineEdit(self)
        self.speed_limit_input.setGeometry(QtCore.QRect(160, 130, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.speed_limit_input.setFont(font)
        self.speed_limit_input.setObjectName("speed_limit_input")
        self.label_8 = QtWidgets.QLabel(self)
        self.label_8.setGeometry(QtCore.QRect(240, 130, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.authority_label = QtWidgets.QLabel(self)
        self.authority_label.setGeometry(QtCore.QRect(20, 180, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.authority_label.setFont(font)
        self.authority_label.setObjectName("authority_label")
        self.authority_input = QtWidgets.QLineEdit(self)
        self.authority_input.setGeometry(QtCore.QRect(160, 180, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.authority_input.setFont(font)
        self.authority_input.setObjectName("authority_input")
        self.label_9 = QtWidgets.QLabel(self)
        self.label_9.setGeometry(QtCore.QRect(240, 180, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.commanded_speed_label = QtWidgets.QLabel(self)
        self.commanded_speed_label.setGeometry(QtCore.QRect(20, 60, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.commanded_speed_label.setFont(font)
        self.commanded_speed_label.setObjectName("commanded_speed_label")
        self.cmd_speed_input = QtWidgets.QLineEdit(self)
        self.cmd_speed_input.setGeometry(QtCore.QRect(160, 70, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.cmd_speed_input.setFont(font)
        self.cmd_speed_input.setObjectName("cmd_speed_input")
        self.label_10 = QtWidgets.QLabel(self)
        self.label_10.setGeometry(QtCore.QRect(240, 70, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.speed_limit_label_2 = QtWidgets.QLabel(self)
        self.speed_limit_label_2.setGeometry(QtCore.QRect(20, 220, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.speed_limit_label_2.setFont(font)
        self.speed_limit_label_2.setObjectName("speed_limit_label_2")
        self.beacon_input = QtWidgets.QLineEdit(self)
        self.beacon_input.setGeometry(QtCore.QRect(20, 250, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.beacon_input.setFont(font)
        self.beacon_input.setObjectName("beacon_input")
        self.train_engine_box = QtWidgets.QCheckBox(self)
        self.train_engine_box.setGeometry(QtCore.QRect(330, 90, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.train_engine_box.setFont(font)
        self.train_engine_box.setObjectName("train_engine_box")
        self.signal_pickup_box = QtWidgets.QCheckBox(self)
        self.signal_pickup_box.setGeometry(QtCore.QRect(330, 130, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.signal_pickup_box.setFont(font)
        self.signal_pickup_box.setObjectName("signal_pickup_box")
        self.brake_box = QtWidgets.QCheckBox(self)
        self.brake_box.setGeometry(QtCore.QRect(330, 170, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.brake_box.setFont(font)
        self.brake_box.setObjectName("brake_box")
        self.power_label = QtWidgets.QLabel(self)
        self.power_label.setGeometry(QtCore.QRect(310, 250, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.power_label.setFont(font)
        self.power_label.setObjectName("power_label")
        self.power = QtWidgets.QLabel(self)
        self.power.setGeometry(QtCore.QRect(370, 250, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.power.setFont(font)
        self.power.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.power.setObjectName("power")
        self.power_label_2 = QtWidgets.QLabel(self)
        self.power_label_2.setGeometry(QtCore.QRect(450, 250, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.power_label_2.setFont(font)
        self.power_label_2.setObjectName("power_label_2")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        self._handler()

        self.train_engine_box.toggled.connect(
            lambda: self._train_controller.set_engine_fault(
                self.train_engine_box.isChecked()
            )
        )
        self.brake_box.toggled.connect(
            lambda: self._train_controller.set_brake_fault(self.brake_box.isChecked())
        )
        self.signal_pickup_box.toggled.connect(
            lambda: self._train_controller.set_signal_fault(
                self.signal_pickup_box.isChecked()
            )
        )

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "TestUI"))
        self.speed_label.setText(_translate("self", "Train's Speed:"))
        self.label_7.setText(_translate("self", "mph"))
        self.label_17.setText(_translate("self", "Emergency Brake"))
        self.e_brake_off_btn.setText(_translate("self", "OFF"))
        self.e_brake_on_btn.setText(_translate("self", "ON"))
        self.speed_limit_label.setText(_translate("self", "Speed Limit:"))
        self.label_8.setText(_translate("self", "mph"))
        self.authority_label.setText(_translate("self", "Authority:"))
        self.label_9.setText(_translate("self", "miles"))
        self.commanded_speed_label.setText(_translate("self", "Commanded \n" " Speed:"))
        self.label_10.setText(_translate("self", "mph"))
        self.speed_limit_label_2.setText(_translate("self", "Beacon"))
        self.train_engine_box.setText(_translate("self", "Train Engine Fault"))
        self.signal_pickup_box.setText(_translate("self", "Signal Pickup Fault"))
        self.brake_box.setText(_translate("self", "Brake Fault"))
        self.power_label.setText(_translate("self", "Power:"))
        self.power_label_2.setText(_translate("Form", "Newtons"))

        self.speed_input.returnPressed.connect(
            lambda: self._train_controller.set_train_speed(int(self.speed_input.text()))
            if self.speed_input.text().isdigit() and int(self.speed_input.text()) >= 0
            else self._train_controller.get_current_speed()
        )
        self.speed_limit_input.returnPressed.connect(
            lambda: self._train_controller.set_speed_limit(
                int(self.speed_limit_input.text())
            )
            if self.speed_limit_input.text().isdigit()
            and int(self.speed_limit_input.text()) >= 0
            else self._train_controller.get_speed_limit()
        )
        self.cmd_speed_input.returnPressed.connect(
            lambda: self._train_controller.set_commanded_speed(
                int(self.cmd_speed_input.text())
            )
            if self.cmd_speed_input.text().isdigit()
            and int(self.cmd_speed_input.text()) >= 0
            else self._train_controller.get_commanded_speed()
        )
        self.authority_input.returnPressed.connect(
            lambda: self._train_controller.set_authority(
                int(self.authority_input.text())
            )
            if self.authority_input.text().isdigit()
            and int(self.authority_input.text()) >= 0
            else self._train_controller.get_authority()
        )
        self.beacon_input.returnPressed.connect(
            lambda: self._train_controller.set_beacon(self.beacon_input.text())
        )

        self.e_brake_off_btn.clicked.connect(
            lambda: self._train_controller.set_emergency_brake(False)
        )
        self.e_brake_on_btn.clicked.connect(
            lambda: self._train_controller.set_emergency_brake(True)
        )

    def _update(self):
        _translate = QtCore.QCoreApplication.translate
        self.power.setText(
            _translate("self", str(self._train_controller.calculate_power()))
        )
        self._check_e_brake()

    def _handler(self):
        self.timer = QTimer(self)
        self.timer.setInterval(100)
        self.timer.timeout.connect(self._update)
        self.timer.start()

    def _check_e_brake(self):
        if self._train_controller.get_emergency_brake():
            self.e_brake_off_btn.setStyleSheet("background-color : white")
            self.e_brake_on_btn.setStyleSheet("background-color : cyan")
        else:
            self.e_brake_off_btn.setStyleSheet("background-color : cyan")
            self.e_brake_on_btn.setStyleSheet("background-color : white")


if __name__ == "__main__":
    app = QApplication(sys.argv)
    tc = TrainController()

    e = DriverUI(tc)
    e1 = TestUI(tc)
    e2 = EngineerUI(tc)
    sys.exit(app.exec_())
