import serial

port = serial.Serial('COM3',115200)
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Testui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)

class Ui_mian_window(object):
    def setupUi(self, mian_window):
        mian_window.setObjectName("mian_window")
        mian_window.resize(1139, 506)
        self.centralwidget = QtWidgets.QWidget(mian_window)
        self.centralwidget.setObjectName("centralwidget")
        self.block_number = QtWidgets.QLabel(self.centralwidget)
        self.block_number.setGeometry(QtCore.QRect(40, 100, 101, 41))
        self.block_number.setObjectName("block_number")
        self.block_number_combo = QtWidgets.QComboBox(self.centralwidget)
        self.block_number_combo.setGeometry(QtCore.QRect(330, 100, 111, 41))
        self.block_number_combo.setObjectName("block_number_combo")
        self.block_number_combo.addItem("")
        self.block_number_combo.addItem("")
        self.block_number_combo.addItem("")
        self.block_number_combo.addItem("")
        self.block_number_combo.addItem("")
        self.block_number_combo.addItem("")
        self.block_number_combo.addItem("")
        self.block_number_combo.addItem("")
        self.block_number_combo.addItem("")
        self.block_number_combo.addItem("")
        self.block_oc_in = QtWidgets.QLabel(self.centralwidget)
        self.block_oc_in.setGeometry(QtCore.QRect(40, 160, 101, 41))
        self.block_oc_in.setObjectName("block_oc_in")
        self.block_oc_output = QtWidgets.QLabel(self.centralwidget)
        self.block_oc_output.setGeometry(QtCore.QRect(330, 200, 91, 41))
        self.block_oc_output.setObjectName("block_oc_output")
        self.block_title = QtWidgets.QLabel(self.centralwidget)
        self.block_title.setGeometry(QtCore.QRect(240, 40, 81, 41))
        self.block_title.setObjectName("block_title")
        self.block_oc_out = QtWidgets.QLabel(self.centralwidget)
        self.block_oc_out.setGeometry(QtCore.QRect(40, 200, 111, 51))
        self.block_oc_out.setObjectName("block_oc_out")
        self.block_is_oc = QtWidgets.QCheckBox(self.centralwidget)
        self.block_is_oc.setGeometry(QtCore.QRect(330, 140, 111, 51))
        self.block_is_oc.setObjectName("block_is_oc")
        self.oc_confirm = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.oc_checked())
        self.oc_confirm.setGeometry(QtCore.QRect(470, 160, 101, 20))
        self.oc_confirm.setObjectName("oc_confirm")
        self.switch_positions = QtWidgets.QLabel(self.centralwidget)
        self.switch_positions.setGeometry(QtCore.QRect(40, 250, 101, 51))
        self.switch_positions.setObjectName("switch_positions")
        self.light_state = QtWidgets.QLabel(self.centralwidget)
        self.light_state.setGeometry(QtCore.QRect(40, 300, 101, 41))
        self.light_state.setObjectName("light_state")
        self.track_status = QtWidgets.QLabel(self.centralwidget)
        self.track_status.setGeometry(QtCore.QRect(40, 350, 101, 51))
        self.track_status.setObjectName("track_status")
        self.railway_crossing = QtWidgets.QLabel(self.centralwidget)
        self.railway_crossing.setGeometry(QtCore.QRect(40, 400, 111, 41))
        self.railway_crossing.setObjectName("railway_crossing")
        self.general_label = QtWidgets.QLabel(self.centralwidget)
        self.general_label.setGeometry(QtCore.QRect(820, 50, 101, 31))
        self.general_label.setObjectName("general_label")
        self.suggusted_speed_2 = QtWidgets.QLabel(self.centralwidget)
        self.suggusted_speed_2.setGeometry(QtCore.QRect(660, 100, 111, 31))
        self.suggusted_speed_2.setObjectName("suggusted_speed_2")
        self.commanded_speed = QtWidgets.QLabel(self.centralwidget)
        self.commanded_speed.setGeometry(QtCore.QRect(660, 140, 101, 41))
        self.commanded_speed.setObjectName("commanded_speed")
        self.commanded_speed_2 = QtWidgets.QLabel(self.centralwidget)
        self.commanded_speed_2.setGeometry(QtCore.QRect(840, 140, 71, 41))
        self.commanded_speed_2.setObjectName("commanded_speed_2")
        self.suggusted_speen_in = QtWidgets.QTextEdit(self.centralwidget)
        self.suggusted_speen_in.setGeometry(QtCore.QRect(840, 100, 161, 41))
        self.suggusted_speen_in.setObjectName("suggusted_speen_in")
        self.authority_input = QtWidgets.QTextEdit(self.centralwidget)
        self.authority_input.setGeometry(QtCore.QRect(840, 180, 161, 41))
        self.authority_input.setObjectName("authority_input")
        self.authority_out = QtWidgets.QLabel(self.centralwidget)
        self.authority_out.setGeometry(QtCore.QRect(660, 250, 161, 21))
        self.authority_out.setObjectName("authority_out")
        self.authority_output = QtWidgets.QLabel(self.centralwidget)
        self.authority_output.setGeometry(QtCore.QRect(840, 250, 101, 21))
        self.authority_output.setObjectName("authority_output")
        self.speed_confirm = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.speed_confirm_clicked())
        self.speed_confirm.setGeometry(QtCore.QRect(1030, 110, 101, 21))
        self.speed_confirm.setObjectName("speed_confirm")
        self.authority_confirm = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.authority_confirm_clicked())
        self.authority_confirm.setGeometry(QtCore.QRect(1030, 190, 101, 21))
        self.authority_confirm.setObjectName("authority_confirm")
        self.authority_in = QtWidgets.QLabel(self.centralwidget)
        self.authority_in.setGeometry(QtCore.QRect(660, 180, 111, 41))
        self.authority_in.setObjectName("authority_in")
        self.switch_position_in = QtWidgets.QTextEdit(self.centralwidget)
        self.switch_position_in.setGeometry(QtCore.QRect(320, 250, 191, 41))
        self.switch_position_in.setObjectName("switch_position_in")
        self.light_state_in = QtWidgets.QTextEdit(self.centralwidget)
        self.light_state_in.setGeometry(QtCore.QRect(320, 300, 191, 41))
        self.light_state_in.setObjectName("light_state_in")
        self.track_status_in = QtWidgets.QTextEdit(self.centralwidget)
        self.track_status_in.setGeometry(QtCore.QRect(320, 350, 191, 41))
        self.track_status_in.setObjectName("track_status_in")
        self.railway_crossing_in = QtWidgets.QTextEdit(self.centralwidget)
        self.railway_crossing_in.setGeometry(QtCore.QRect(320, 400, 191, 41))
        self.railway_crossing_in.setObjectName("railway_crossing_in")
        self.switch_pos_confirm = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.switch_confirm_clicked())
        self.switch_pos_confirm.setGeometry(QtCore.QRect(530, 260, 101, 20))
        self.switch_pos_confirm.setObjectName("switch_pos_confirm")
        self.light_state_confirm = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.light_confirm_clicked())
        self.light_state_confirm.setGeometry(QtCore.QRect(530, 310, 101, 20))
        self.light_state_confirm.setObjectName("light_state_confirm")
        self.track_status_confirm = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.status_confirm_clicked())
        self.track_status_confirm.setGeometry(QtCore.QRect(530, 360, 101, 20))
        self.track_status_confirm.setObjectName("track_status_confirm")
        self.railway_crossing_confirm = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.crossing_confirm_clicked())
        self.railway_crossing_confirm.setGeometry(QtCore.QRect(530, 410, 101, 20))
        self.railway_crossing_confirm.setObjectName("railway_crossing_confirm")
        mian_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mian_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1139, 22))
        self.menubar.setObjectName("menubar")
        mian_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mian_window)
        self.statusbar.setObjectName("statusbar")
        mian_window.setStatusBar(self.statusbar)

        self.retranslateUi(mian_window)
        QtCore.QMetaObject.connectSlotsByName(mian_window)

    def crossing_confirm_clicked(self):
        word = "rc."+(self.block_number_combo.itemText(self.block_number_combo.currentIndex())) + str(self.railway_crossing_in.toPlainText()) + ";"
        port.write(bytes(word, 'utf-8'))

    def status_confirm_clicked(self):
        word = "ts."+(self.block_number_combo.itemText(self.block_number_combo.currentIndex())) + str(self.track_status_in.toPlainText()) + ";"
        port.write(bytes(word, 'utf-8'))

    def light_confirm_clicked(self):
        word = "ls."+(self.block_number_combo.itemText(self.block_number_combo.currentIndex())) + str(self.light_state_in.toPlainText()) + ";"
        port.write(bytes(word, 'utf-8'))

    def switch_confirm_clicked(self):
        #port.write(bytes("sp." + str(self.suggusted_speen_in.toPlainText()) + ";", 'utf-8'))
        word = "sp."+(self.block_number_combo.itemText(self.block_number_combo.currentIndex())) + str(self.switch_position_in.toPlainText())+";"
        port.write(bytes(word, 'utf-8'))
        #self.commanded_speed_2.setText(str(self.suggusted_speen_in.toPlainText()) + "mph")

    def oc_checked(self):
        if self.block_is_oc.isChecked() == True:
            word = self.block_number_combo.itemText(self.block_number_combo.currentIndex())+"Occupied."
            port.write(bytes(word, 'utf-8'))
            self.block_oc_output.setText("Occupied")
        else:
            word = (self.block_number_combo.itemText(self.block_number_combo.currentIndex()))+"Not Occupied."
            port.write(bytes(word, 'utf-8'))
            self.block_oc_output.setText("Not Occupied")

    def speed_confirm_clicked(self):
        port.write(bytes("ss."+str(self.suggusted_speen_in.toPlainText())+";", 'utf-8'))
        self.commanded_speed_2.setText(str(self.suggusted_speen_in.toPlainText())+"mph")

    def authority_confirm_clicked(self):
        port.write(bytes("au."+str(self.authority_input.toPlainText())+";", 'utf-8'))
        self.authority_output.setText(str(self.authority_input.toPlainText())+"m")

    def retranslateUi(self, mian_window):
        _translate = QtCore.QCoreApplication.translate
        mian_window.setWindowTitle(_translate("mian_window", "MainWindow"))
        self.block_number.setText(_translate("mian_window", "Block Number:"))
        self.block_number_combo.setItemText(0, _translate("mian_window", "1"))
        self.block_number_combo.setItemText(1, _translate("mian_window", "2"))
        self.block_number_combo.setItemText(2, _translate("mian_window", "3"))
        self.block_number_combo.setItemText(3, _translate("mian_window", "4"))
        self.block_number_combo.setItemText(4, _translate("mian_window", "5"))
        self.block_number_combo.setItemText(5, _translate("mian_window", "6"))
        self.block_number_combo.setItemText(6, _translate("mian_window", "7"))
        self.block_number_combo.setItemText(7, _translate("mian_window", "8"))
        self.block_number_combo.setItemText(8, _translate("mian_window", "9"))
        self.block_number_combo.setItemText(9, _translate("mian_window", "10"))
        self.block_oc_in.setText(_translate("mian_window", "Block Occupancy In:"))
        self.block_oc_output.setText(_translate("mian_window", "0"))
        self.block_title.setText(_translate("mian_window", "Block Specific"))
        self.block_oc_out.setText(_translate("mian_window", "Block Occupancy Out:"))
        self.block_is_oc.setText(_translate("mian_window", "Occupied"))
        self.oc_confirm.setText(_translate("mian_window", "Confirm"))
        self.switch_positions.setText(_translate("mian_window", "Switch Positions:"))
        self.light_state.setText(_translate("mian_window", "Light States:"))
        self.track_status.setText(_translate("mian_window", "Track Status:"))
        self.railway_crossing.setText(_translate("mian_window", "Railway Crossing:"))
        self.general_label.setText(_translate("mian_window", "General"))
        self.suggusted_speed_2.setText(_translate("mian_window", "Suggusted Speed:"))
        self.commanded_speed.setText(_translate("mian_window", "Commanded Speed:"))
        self.commanded_speed_2.setText(_translate("mian_window", "mph"))
        self.authority_out.setText(_translate("mian_window", "Authority out:"))
        self.authority_output.setText(_translate("mian_window", "m"))
        self.speed_confirm.setText(_translate("mian_window", "Confirm"))
        self.authority_confirm.setText(_translate("mian_window", "Confirm"))
        self.authority_in.setText(_translate("mian_window", "Authority in:"))
        self.switch_pos_confirm.setText(_translate("mian_window", "Confirm"))
        self.light_state_confirm.setText(_translate("mian_window", "Confirm"))
        self.track_status_confirm.setText(_translate("mian_window", "Confirm"))
        self.railway_crossing_confirm.setText(_translate("mian_window", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mian_window = QtWidgets.QMainWindow()
    ui = Ui_mian_window()
    ui.setupUi(mian_window)
    mian_window.show()
    sys.exit(app.exec_())
