# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from train_model.train_model import TrainModel
from PyQt5.QtWidgets import *
from PyQt5 import uic
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)

class Ui_MainUI(object):
    def __init__(self, trainModel: TrainModel):
        super().__init__()
        self.trainModel = trainModel

    def setupUi(self, MainUI):
        MainUI.setObjectName("MainUI")
        MainUI.resize(638, 853)
        self.centralwidget = QtWidgets.QWidget(MainUI)
        self.centralwidget.setObjectName("centralwidget")
        self.ForceAreaMAIN = QtWidgets.QMdiArea(self.centralwidget)
        self.ForceAreaMAIN.setGeometry(QtCore.QRect(10, 80, 291, 171))
        self.ForceAreaMAIN.setObjectName("ForceAreaMAIN")
        self.TrainModelSimTitleMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.TrainModelSimTitleMAIN.setGeometry(QtCore.QRect(10, 0, 581, 41))
        self.TrainModelSimTitleMAIN.setObjectName("TrainModelSimTitleMAIN")
        self.forceResultBoxMAIN = QtWidgets.QTextEdit(self.centralwidget)
        self.forceResultBoxMAIN.setEnabled(False)
        self.forceResultBoxMAIN.setGeometry(QtCore.QRect(20, 110, 271, 131))
        self.forceResultBoxMAIN.setObjectName("forceResultBoxMAIN")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 90, 101, 16))
        self.label_5.setObjectName("label_5")
        self.forceblocktitleMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.forceblocktitleMAIN.setGeometry(QtCore.QRect(10, 50, 291, 31))
        self.forceblocktitleMAIN.setObjectName("forceblocktitleMAIN")
        self.VactualAreaMAIN = QtWidgets.QMdiArea(self.centralwidget)
        self.VactualAreaMAIN.setGeometry(QtCore.QRect(10, 290, 291, 171))
        self.VactualAreaMAIN.setObjectName("VactualAreaMAIN")
        self.AccelAreaMAIN = QtWidgets.QMdiArea(self.centralwidget)
        self.AccelAreaMAIN.setGeometry(QtCore.QRect(10, 500, 291, 171))
        self.AccelAreaMAIN.setObjectName("AccelAreaMAIN")
        self.VactualblocktitleMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.VactualblocktitleMAIN.setGeometry(QtCore.QRect(10, 260, 291, 31))
        self.VactualblocktitleMAIN.setObjectName("VactualblocktitleMAIN")
        self.AccelblocktitleMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.AccelblocktitleMAIN.setGeometry(QtCore.QRect(10, 470, 291, 31))
        self.AccelblocktitleMAIN.setObjectName("AccelblocktitleMAIN")
        self.VactualResultBoxMAIN = QtWidgets.QTextEdit(self.centralwidget)
        self.VactualResultBoxMAIN.setEnabled(False)
        self.VactualResultBoxMAIN.setGeometry(QtCore.QRect(20, 320, 271, 131))
        self.VactualResultBoxMAIN.setObjectName("VactualResultBoxMAIN")
        self.accelResultBoxMAIN = QtWidgets.QTextEdit(self.centralwidget)
        self.accelResultBoxMAIN.setEnabled(False)
        self.accelResultBoxMAIN.setGeometry(QtCore.QRect(20, 530, 271, 131))
        self.accelResultBoxMAIN.setObjectName("accelResultBoxMAIN")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 300, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 510, 141, 16))
        self.label_7.setObjectName("label_7")
        self.radioButton_10 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_10.setGeometry(QtCore.QRect(420, 700, 95, 20))
        self.radioButton_10.setObjectName("radioButton_10")
        self.ServiceBrakeAreaMAIN = QtWidgets.QMdiArea(self.centralwidget)
        self.ServiceBrakeAreaMAIN.setGeometry(QtCore.QRect(310, 260, 181, 71))
        self.ServiceBrakeAreaMAIN.setObjectName("ServiceBrakeAreaMAIN")
        self.LdoorAreaMAIN = QtWidgets.QMdiArea(self.centralwidget)
        self.LdoorAreaMAIN.setGeometry(QtCore.QRect(310, 680, 181, 91))
        self.LdoorAreaMAIN.setObjectName("LdoorAreaMAIN")
        self.StatusUpdateAreaTEST = QtWidgets.QMdiArea(self.centralwidget)
        self.StatusUpdateAreaTEST.setGeometry(QtCore.QRect(310, 80, 181, 141))
        self.StatusUpdateAreaTEST.setObjectName("StatusUpdateAreaTEST")
        self.EbrakeAreaMAIN = QtWidgets.QMdiArea(self.centralwidget)
        self.EbrakeAreaMAIN.setGeometry(QtCore.QRect(310, 340, 181, 71))
        self.EbrakeAreaMAIN.setObjectName("EbrakeAreaMAIN")
        self.BrakeFailBoxMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.BrakeFailBoxMAIN.setGeometry(QtCore.QRect(320, 130, 131, 41))
        self.BrakeFailBoxMAIN.setObjectName("BrakeFailBoxMAIN")
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_15.setGeometry(QtCore.QRect(320, 590, 91, 71))
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_11.setGeometry(QtCore.QRect(310, 50, 181, 31))
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(460, 180, 55, 16))
        self.label_12.setObjectName("label_12")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(320, 350, 101, 51))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.powerFailBoxMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.powerFailBoxMAIN.setGeometry(QtCore.QRect(320, 90, 131, 41))
        self.powerFailBoxMAIN.setObjectName("powerFailBoxMAIN")
        self.LightsAreaMAIN = QtWidgets.QMdiArea(self.centralwidget)
        self.LightsAreaMAIN.setGeometry(QtCore.QRect(310, 420, 181, 71))
        self.LightsAreaMAIN.setObjectName("LightsAreaMAIN")
        self.SignalFailBoxMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.SignalFailBoxMAIN.setGeometry(QtCore.QRect(320, 170, 131, 41))
        self.SignalFailBoxMAIN.setObjectName("SignalFailBoxMAIN")
        self.radioButton_8 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_8.setGeometry(QtCore.QRect(420, 600, 95, 20))
        self.radioButton_8.setObjectName("radioButton_8")
        self.ControlsBoxMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.ControlsBoxMAIN.setGeometry(QtCore.QRect(310, 230, 181, 31))
        self.ControlsBoxMAIN.setObjectName("ControlsBoxMAIN")
        self.RdoorAreaMAIN = QtWidgets.QMdiArea(self.centralwidget)
        self.RdoorAreaMAIN.setGeometry(QtCore.QRect(310, 580, 181, 91))
        self.RdoorAreaMAIN.setObjectName("RdoorAreaMAIN")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(460, 140, 55, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(460, 100, 55, 16))
        self.label_14.setObjectName("label_14")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(320, 270, 101, 51))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_10.setGeometry(QtCore.QRect(320, 690, 101, 71))
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_16.setGeometry(QtCore.QRect(320, 590, 101, 71))
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.serviceBrakeoutputMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.serviceBrakeoutputMAIN.setGeometry(QtCore.QRect(430, 270, 51, 51))
        self.serviceBrakeoutputMAIN.setObjectName("serviceBrakeoutputMAIN")
        self.EbrakeoutputMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.EbrakeoutputMAIN.setGeometry(QtCore.QRect(430, 350, 51, 51))
        self.EbrakeoutputMAIN.setObjectName("EbrakeoutputMAIN")
        self.LightoutputMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.LightoutputMAIN.setGeometry(QtCore.QRect(430, 430, 51, 51))
        self.LightoutputMAIN.setObjectName("LightoutputMAIN")
        self.RdooroutputMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.RdooroutputMAIN.setGeometry(QtCore.QRect(430, 590, 51, 71))
        self.RdooroutputMAIN.setObjectName("RdooroutputMAIN")
        self.LdooroutputMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.LdooroutputMAIN.setGeometry(QtCore.QRect(430, 690, 51, 71))
        self.LdooroutputMAIN.setObjectName("LdooroutputMAIN")
        self.QuickMetricsTitleBox_MAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.QuickMetricsTitleBox_MAIN.setGeometry(QtCore.QRect(500, 50, 111, 31))
        self.QuickMetricsTitleBox_MAIN.setObjectName("QuickMetricsTitleBox_MAIN")
        self.TrackStatusblocktitleMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.TrackStatusblocktitleMAIN.setGeometry(QtCore.QRect(160, 680, 141, 51))
        self.TrackStatusblocktitleMAIN.setObjectName("TrackStatusblocktitleMAIN")
        self.TrackStatusResultBoxTEST = QtWidgets.QTextBrowser(self.centralwidget)
        self.TrackStatusResultBoxTEST.setGeometry(QtCore.QRect(170, 740, 121, 71))
        self.TrackStatusResultBoxTEST.setObjectName("TrackStatusResultBoxTEST")
        self.LdoorAreaTEST_4 = QtWidgets.QMdiArea(self.centralwidget)
        self.LdoorAreaTEST_4.setGeometry(QtCore.QRect(160, 710, 141, 111))
        self.LdoorAreaTEST_4.setObjectName("LdoorAreaTEST_4")
        self.LdoorAreaTEST_3 = QtWidgets.QMdiArea(self.centralwidget)
        self.LdoorAreaTEST_3.setGeometry(QtCore.QRect(10, 710, 141, 111))
        self.LdoorAreaTEST_3.setObjectName("LdoorAreaTEST_3")
        self.BeaconResultBoxMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.BeaconResultBoxMAIN.setGeometry(QtCore.QRect(20, 720, 121, 71))
        self.BeaconResultBoxMAIN.setObjectName("BeaconResultBoxMAIN")
        self.BeaconblocktitleMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.BeaconblocktitleMAIN.setGeometry(QtCore.QRect(10, 680, 141, 41))
        self.BeaconblocktitleMAIN.setObjectName("BeaconblocktitleMAIN")
        self.TempMetricsResultBoxMAIN_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.TempMetricsResultBoxMAIN_2.setGeometry(QtCore.QRect(500, 80, 111, 31))
        self.TempMetricsResultBoxMAIN_2.setObjectName("TempMetricsResultBoxMAIN_2")
        self.tempControlip_MAIN = QtWidgets.QSpinBox(self.centralwidget)
        self.tempControlip_MAIN.setGeometry(QtCore.QRect(170, 690, 61, 21))
        self.tempControlip_MAIN.setObjectName("tempControlip_TEST")
        self.TempEditSetMAIN = QtWidgets.QPushButton(self.centralwidget)
        self.TempEditSetMAIN.setGeometry(QtCore.QRect(180, 720, 31, 21))
        self.TempEditSetMAIN.setObjectName("TempEditSetMAIN")
        self.AuthorityMetricsResultBoxMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.AuthorityMetricsResultBoxMAIN.setGeometry(QtCore.QRect(500, 110, 111, 31))
        self.AuthorityMetricsResultBoxMAIN.setObjectName("AuthorityMetricsResultBoxMAIN")
        self.SpeedLimitMetricsResultBoxMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.SpeedLimitMetricsResultBoxMAIN.setGeometry(QtCore.QRect(500, 140, 111, 31))
        self.SpeedLimitMetricsResultBoxMAIN.setObjectName("SpeedLimitMetricsResultBoxMAIN")
        self.ElevationMetricsResultBoxMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.ElevationMetricsResultBoxMAIN.setGeometry(QtCore.QRect(500, 230, 111, 31))
        self.ElevationMetricsResultBoxMAIN.setObjectName("ElevationMetricsResultBoxMAIN")
        self.DeccelLimitMetricsResultBoxMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.DeccelLimitMetricsResultBoxMAIN.setGeometry(QtCore.QRect(500, 200, 111, 31))
        self.DeccelLimitMetricsResultBoxMAIN.setObjectName("DeccelLimitMetricsResultBoxMAIN")
        self.AccelLimitMetricsResultBoxMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.AccelLimitMetricsResultBoxMAIN.setGeometry(QtCore.QRect(500, 170, 111, 31))
        self.AccelLimitMetricsResultBoxMAIN.setObjectName("AccelLimitMetricsResultBoxMAIN")
        self.GradeMetricsResultBoxMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.GradeMetricsResultBoxMAIN.setGeometry(QtCore.QRect(500, 260, 111, 31))
        self.GradeMetricsResultBoxMAIN.setObjectName("GradeMetricsResultBoxMAIN")
        self.quickMetricsbaropMAIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.quickMetricsbaropMAIN.setGeometry(QtCore.QRect(500, 0, 111, 41))
        self.quickMetricsbaropMAIN.setObjectName("quickMetricsbaropMAIN")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_12.setGeometry(QtCore.QRect(320, 510, 101, 51))
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.ExtrernalLightsbutton_offTEST = QtWidgets.QRadioButton(self.centralwidget)
        self.ExtrernalLightsbutton_offTEST.setGeometry(QtCore.QRect(430, 550, 95, 20))
        self.ExtrernalLightsbutton_offTEST.setObjectName("ExtrernalLightsbutton_offTEST")
        self.LightsAreaTEST_2 = QtWidgets.QMdiArea(self.centralwidget)
        self.LightsAreaTEST_2.setGeometry(QtCore.QRect(310, 500, 181, 71))
        self.LightsAreaTEST_2.setObjectName("LightsAreaTEST_2")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(320, 430, 101, 51))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.LightoutputMAIN_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.LightoutputMAIN_2.setGeometry(QtCore.QRect(430, 510, 51, 51))
        self.LightoutputMAIN_2.setObjectName("LightoutputMAIN_2")
        self.TempResultBoxTEST = QtWidgets.QTextEdit(self.centralwidget)
        self.TempResultBoxTEST.setEnabled(False)
        self.TempResultBoxTEST.setGeometry(QtCore.QRect(170, 720, 121, 71))
        self.TempResultBoxTEST.setObjectName("TempResultBoxTEST")
        self.ServiceBrakeAreaTEST_2 = QtWidgets.QMdiArea(self.centralwidget)
        self.ServiceBrakeAreaTEST_2.setGeometry(QtCore.QRect(500, 340, 111, 71))
        self.ServiceBrakeAreaTEST_2.setObjectName("ServiceBrakeAreaTEST_2")
        self.ControlsBoxTEST_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.ControlsBoxTEST_2.setGeometry(QtCore.QRect(500, 320, 111, 31))
        self.ControlsBoxTEST_2.setObjectName("ControlsBoxTEST_2")
        self.SignalPickupFailure_TEST = QtWidgets.QCheckBox(self.centralwidget)
        self.SignalPickupFailure_TEST.setGeometry(QtCore.QRect(510, 350, 101, 20))
        self.SignalPickupFailure_TEST.setObjectName("SignalPickupFailure_TEST")
        self.ServiceBrakeFailure_TEST_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.ServiceBrakeFailure_TEST_2.setGeometry(QtCore.QRect(510, 390, 101, 20))
        self.ServiceBrakeFailure_TEST_2.setObjectName("ServiceBrakeFailure_TEST_2")
        self.eBrakeFailure_TEST = QtWidgets.QCheckBox(self.centralwidget)
        self.eBrakeFailure_TEST.setGeometry(QtCore.QRect(510, 370, 91, 20))
        self.eBrakeFailure_TEST.setObjectName("eBrakeFailure_TEST")

        self.ForceAreaMAIN.raise_()
        self.TrainModelSimTitleMAIN.raise_()
        self.forceResultBoxMAIN.raise_()
        self.label_5.raise_()
        self.forceblocktitleMAIN.raise_()
        self.VactualAreaMAIN.raise_()
        self.AccelAreaMAIN.raise_()
        self.VactualblocktitleMAIN.raise_()
        self.AccelblocktitleMAIN.raise_()
        self.VactualResultBoxMAIN.raise_()
        self.accelResultBoxMAIN.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.radioButton_10.raise_()
        self.ServiceBrakeAreaMAIN.raise_()
        self.LdoorAreaMAIN.raise_()
        self.StatusUpdateAreaTEST.raise_()
        self.EbrakeAreaMAIN.raise_()
        self.BrakeFailBoxMAIN.raise_()
        self.textBrowser_15.raise_()
        self.textBrowser_11.raise_()
        self.label_12.raise_()
        self.textBrowser_7.raise_()
        self.powerFailBoxMAIN.raise_()
        self.LightsAreaMAIN.raise_()
        self.SignalFailBoxMAIN.raise_()
        self.radioButton_8.raise_()
        self.ControlsBoxMAIN.raise_()
        self.RdoorAreaMAIN.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.textBrowser_6.raise_()
        self.textBrowser_10.raise_()
        self.textBrowser_16.raise_()
        self.serviceBrakeoutputMAIN.raise_()
        self.EbrakeoutputMAIN.raise_()
        self.LightoutputMAIN.raise_()
        self.RdooroutputMAIN.raise_()
        self.LdooroutputMAIN.raise_()
        self.QuickMetricsTitleBox_MAIN.raise_()
        self.TrackStatusblocktitleMAIN.raise_()
        self.TrackStatusResultBoxTEST.raise_()
        self.LdoorAreaTEST_4.raise_()
        self.BeaconblocktitleMAIN.raise_()
        self.LdoorAreaTEST_3.raise_()
        self.BeaconResultBoxMAIN.raise_()
        self.TempMetricsResultBoxMAIN_2.raise_()
        self.AuthorityMetricsResultBoxMAIN.raise_()
        self.SpeedLimitMetricsResultBoxMAIN.raise_()
        self.ElevationMetricsResultBoxMAIN.raise_()
        self.DeccelLimitMetricsResultBoxMAIN.raise_()
        self.AccelLimitMetricsResultBoxMAIN.raise_()
        self.GradeMetricsResultBoxMAIN.raise_()
        self.quickMetricsbaropMAIN.raise_()
        self.ExtrernalLightsbutton_offTEST.raise_()
        self.LightsAreaTEST_2.raise_()
        self.textBrowser_8.raise_()
        self.textBrowser_12.raise_()
        self.LightoutputMAIN_2.raise_()
        self.TempResultBoxTEST.raise_()
        self.tempControlip_MAIN.raise_()
        self.TempEditSetMAIN.raise_()
        self.ServiceBrakeAreaTEST_2.raise_()
        self.ControlsBoxTEST_2.raise_()
        self.SignalPickupFailure_TEST.raise_()
        self.ServiceBrakeFailure_TEST_2.raise_()
        self.eBrakeFailure_TEST.raise_()


        MainUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 638, 26))
        self.menubar.setObjectName("menubar")
        MainUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainUI)
        self.statusbar.setObjectName("statusbar")
        MainUI.setStatusBar(self.statusbar)

        self.retranslateUi(MainUI)
        QtCore.QMetaObject.connectSlotsByName(MainUI)
        # self._handler()

        # add functionality to the main UI (similiar to that in test UI)
        # set default values in the text boxes for the private variable
        self.forceResultBoxMAIN.setText(str(self.trainModel.get_force()))
        self.VactualResultBoxMAIN.setText(str(self.trainModel.calc_actual_velocity()))
        self.accelResultBoxMAIN.setText(str(self.trainModel.calc_acceleration()))
        self.TempMetricsResultBoxMAIN_2.setPlainText(str(self.trainModel.get_temperature()))
        # post the following from track model to text box:
        self.AuthorityMetricsResultBoxMAIN.setPlainText(str(self.trainModel.get_authority()))  # authority
        self.SpeedLimitMetricsResultBoxMAIN.setPlainText(str(self.trainModel.get_speed_limit()))  # speed limit
        self.AccelLimitMetricsResultBoxMAIN.setPlainText(str(self.trainModel.accel_limit))  # accel limit
        self.DeccelLimitMetricsResultBoxMAIN.setPlainText(str(self.trainModel.decel_limit))  # decel limit
        self.ElevationMetricsResultBoxMAIN.setPlainText(str(self.trainModel.get_elevation()))  # elevation
        self.GradeMetricsResultBoxMAIN.setPlainText(str(self.trainModel.get_grade()))  # grade
        self.BeaconResultBoxMAIN.setText(str(self.trainModel.get_beacon()))  # beacon

        # add functionality to buttons: may change this later
        self.TempEditSetMAIN.clicked.connect(self.temp_control)  # set the temperature
    #     # initiate the failure modes
        self.SignalPickupFailure_TEST.toggled.connect(lambda: self.trainModel.set_signal_pickup_failure(self.SignalPickupFailure_TEST.isChecked()))
        self.eBrakeFailure_TEST.toggled.connect(lambda: self.trainModel.set_eBrake_failure(self.eBrakeFailure_TEST.isChecked()))
        self.ServiceBrakeFailure_TEST_2.toggled.connect(lambda: self.trainModel.set_service_brake_failure(self.ServiceBrakeFailure_TEST_2.isChecked()))
    #
    # # update function that continuously gets called and updates the main UI
    # def update(self):
    #     _translate = QtCore.QCoreApplication.translate
    #     try:
    #         self.forceResultBoxMAIN.setText(str(round(self.trainModel.get_force(), 3)))
    #         self.accelResultBoxMAIN.setText(str(round(self.trainModel.get_accel(), 3)))
    #         self.VactualResultBoxMAIN.setText(str(round(self.trainModel.get_actual_velocity(), 3)))
    #         self.BeaconResultBoxMAIN.setText(str(self.trainModel.get_beacon()))
    #         self.TempMetricsResultBoxMAIN_2.setPlainText(f"Temp:{str(self.trainModel.get_temperature())}°")
    #         self.serviceBrakeoutputMAIN.setPlainText(str(self.trainModel.get_service_brake()))
    #         self.EbrakeoutputMAIN.setPlainText(str(self.trainModel.get_e_brake()))
    #         self.LightoutputMAIN.setPlainText(str(self.trainModel.get_internal_lights()))
    #         self.LightoutputMAIN_2.setPlainText(str(self.trainModel.get_external_lights()))
    #         self.RdooroutputMAIN.setPlainText(str(self.trainModel.get_right_doors()))
    #         self.LdooroutputMAIN.setPlainText(str(self.trainModel.get_left_doors()))
    #     except AttributeError:
    #         print("cannot refresh attributes in main UI")
    #     # check for failure modes
    #     self.check_power_failure()
    #     self.check_signal_failure()
    #     self.check_brake_failure()
    #
    # def _handler(self):
    #     self.timer = QTimer()
    #     self.timer.setInterval(100)  # refreshes every time period
    #     self.timer.timeout.connect(self.update)
    #     self.timer.start()
    #
    #
    def temp_control(self):
        # read input from the spin box
        temp = self.tempControlip_MAIN.value()
        self.trainModel.set_temperature(float(temp))

    # check for power failure:
    def check_power_failure(self):
        # if pCmd > Pmax
        if self.trainModel.get_cmd_power() > self.trainModel.Pmax:
            self.powerFailBoxTEST.setText(
                "Power/engine failure")  # display error message
            # refresh force result in the main UI:
            try:
                # refresh force calculation in test UI
                self.ui.powerFailBoxMAIN.setText("Power/engine failure")
            except AttributeError:
                print("")
        else:
            self.powerFailBoxTEST.setText(
                "power status: good")  # clear the error message
            try:
                # refresh force calculation in test UI
                self.ui.powerFailBoxMAIN.setText("power status: good")
            except AttributeError:
                print("")

    # check signal-pcikup failure:
    def check_signal_failure(self):
        if self.trainModel.get_signal_pickup_failure():
            self.SignalFailBoxTEST.setText(
                "Signal Pickup Failure")  # display error message
            # refresh force result in the main UI:
            try:
                self.ui.SignalFailBoxMAIN.setText(
                    "Signal Pickup Failure")  # refresh in main UI
            except AttributeError:
                print("")
        else:
            self.SignalFailBoxTEST.setText(
                "signal pick-up: good")  # clear error message
            # refresh force result in the main UI:
            try:
                self.ui.SignalFailBoxMAIN.setText(
                    "signal pick-up: good")  # refresh in main UI
            except AttributeError:
                print("")

    # check brake failure:
    def check_brake_failure(self):
        if self.trainModel.get_eBrake_failure():
            self.BrakeFailBoxTEST.setText("Emergency Brake Failure")
            try:
                self.ui.BrakeFailBoxMAIN.setText("Emergency Brake Failure")
            except AttributeError:
                print("")
        elif self.trainModel.get_service_brake_failure():
            self.BrakeFailBoxTEST.setText("Service Brake Failure")
            try:
                self.ui.BrakeFailBoxMAIN.setText("Service Brake Failure")
            except AttributeError:
                print("")
        else:
            self.BrakeFailBoxTEST.setText("Brake status: good")
            try:
                self.ui.BrakeFailBoxMAIN.setText("Brake status: good")
            except AttributeError:
                print("")


    def retranslateUi(self, MainUI):
        _translate = QtCore.QCoreApplication.translate
        MainUI.setWindowTitle(_translate("MainUI", "MainWindow"))
        self.TrainModelSimTitleMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Train Model Simulator</span></p></body></html>"))
        self.forceResultBoxMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_5.setText(_translate("MainUI", "Calculated Force: "))
        self.forceblocktitleMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Force (Newtons) </span></p></body></html>"))
        self.VactualblocktitleMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Actual Velocity (m/s)</span></p></body></html>"))
        self.AccelblocktitleMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Acceleration (m/s</span><span style=\" font-size:10pt; vertical-align:super;\">2</span><span style=\" font-size:10pt;\">)</span></p></body></html>"))
        self.VactualResultBoxMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.accelResultBoxMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_6.setText(_translate("MainUI", "Calculated velocity: "))
        self.label_7.setText(_translate("MainUI", "Calculated acceleration: "))
        self.radioButton_10.setText(_translate("MainUI", "OPEN"))
        self.BrakeFailBoxMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_15.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">Right </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">Doors</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">🚪🚶🏻‍♂️</span></p></body></html>"))
        self.textBrowser_11.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:9pt; font-weight:600;\">🚨</span><span style=\" font-size:9pt; font-weight:600; text-decoration: underline; color:#aa0000;\">Status Updates</span><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:9pt; font-weight:600;\">🚨</span></p></body></html>"))
        self.label_12.setText(_translate("MainUI", "📶"))
        self.textBrowser_7.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600; color:#c80825;\">Emergency </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600; color:#c80825;\">Brake </span><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">🛑</span></p></body></html>"))
        self.powerFailBoxMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.SignalFailBoxMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.radioButton_8.setText(_translate("MainUI", "OPEN"))
        self.ControlsBoxMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; color:#0000ff;\">Controls🔧</span></p></body></html>"))
        self.label_13.setText(_translate("MainUI", "🆘"))
        self.label_14.setText(_translate("MainUI", "⚠️"))
        self.textBrowser_6.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#0000ff;\">Service Brake </span><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">🚫</span></p></body></html>"))
        self.textBrowser_10.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">Left </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">Doors</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">🚪🚶🏻‍♂️</span></p></body></html>"))
        self.textBrowser_16.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">Right </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">Doors</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">🚪🚶🏻‍♂️</span></p></body></html>"))
        self.serviceBrakeoutputMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.EbrakeoutputMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.LightoutputMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.RdooroutputMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.LdooroutputMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.QuickMetricsTitleBox_MAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600; color:#242424;\">Quick Metrics</span></p></body></html>"))
        self.TrackStatusblocktitleMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Temperature 🌡️</p></body></html>"))
        self.TrackStatusResultBoxTEST.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.BeaconResultBoxMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.BeaconblocktitleMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Beacon<span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">🚏</span></p></body></html>"))
        self.TempMetricsResultBoxMAIN_2.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.AuthorityMetricsResultBoxMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.SpeedLimitMetricsResultBoxMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ElevationMetricsResultBoxMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.DeccelLimitMetricsResultBoxMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.AccelLimitMetricsResultBoxMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.GradeMetricsResultBoxMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.quickMetricsbaropMAIN.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_12.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#0000ff;\">Extrernal </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#0000ff;\">Lights</span><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">💡</span></p></body></html>"))
        self.ExtrernalLightsbutton_offTEST.setText(_translate("MainUI", "OFF"))
        self.textBrowser_8.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#0000ff;\">Internal </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#0000ff;\">Lights</span><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">💡</span></p></body></html>"))
        self.LightoutputMAIN_2.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.TempResultBoxTEST.setHtml(_translate("MainUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        # self.TempEditSetMAIN.setText(_translate("MainUI", "Set"))
        # self.ControlsBoxTEST_2.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        #                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        #                                           "p, li { white-space: pre-wrap; }\n"
        #                                           "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
        #                                           "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; color:#aa0000;\">Failures</span></p></body></html>"))
        # self.SignalPickupFailure_TEST.setText(
        #     _translate("TestUI", "Signal Fail"))
        # self.ServiceBrakeFailure_TEST_2.setText(
        #     _translate("TestUI", "S-brake Fail"))
        # self.eBrakeFailure_TEST.setText(_translate("TestUI", "E-brake Fail"))

if __name__ == '__main__':
    import sys
    app = QApplication(sys.argv)
    main_ui = QtWidgets.QMainWindow()
    tm = TrainModel()
    ui = Ui_MainUI(tm)
    ui.setupUi(main_ui)
    main_ui.show()
    sys.exit(app.exec_())


