# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from train_model.train_model import TrainModel
# from train_model.MainUI import Ui_MainUI
from PyQt5.QtWidgets import *
from PyQt5 import uic
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)


class Ui_TestUI(object):
    def __init__(self, trainModel: TrainModel):
        super().__init__()
        self.trainModel = trainModel  # testing this

    def open_window(self):
        # open main ui window
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainUI()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, TestUI):
        TestUI.setObjectName("TestUI")
        TestUI.resize(639, 855)
        self.centralwidget = QtWidgets.QWidget(TestUI)
        self.centralwidget.setObjectName("centralwidget")
        self.poweripBoxTEST = QtWidgets.QTextEdit(self.centralwidget)
        self.poweripBoxTEST.setEnabled(True)
        self.poweripBoxTEST.setGeometry(QtCore.QRect(20, 100, 81, 31))
        self.poweripBoxTEST.setObjectName("poweripBoxTEST")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(700, 210, 55, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.TrainModelSimTitleTEST = QtWidgets.QTextBrowser(
            self.centralwidget)
        self.TrainModelSimTitleTEST.setGeometry(QtCore.QRect(10, 0, 601, 41))
        self.TrainModelSimTitleTEST.setObjectName("TrainModelSimTitleTEST")
        self.CalculateButtonTEST = QtWidgets.QPushButton(self.centralwidget)
        self.CalculateButtonTEST.setEnabled(True)
        self.CalculateButtonTEST.setGeometry(QtCore.QRect(230, 0, 161, 41))
        self.CalculateButtonTEST.setObjectName("CalculateButtonTEST")
        self.forceResultBoxTEST = QtWidgets.QTextEdit(self.centralwidget)
        self.forceResultBoxTEST.setEnabled(False)
        self.forceResultBoxTEST.setGeometry(QtCore.QRect(160, 110, 131, 121))
        self.forceResultBoxTEST.setObjectName("forceResultBoxTEST")
        self.VcmdipBoxTEST = QtWidgets.QTextEdit(self.centralwidget)
        self.VcmdipBoxTEST.setEnabled(True)
        self.VcmdipBoxTEST.setGeometry(QtCore.QRect(20, 150, 81, 31))
        self.VcmdipBoxTEST.setObjectName("VcmdipBoxTEST")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 90, 101, 16))
        self.label_4.setObjectName("label_4")
        self.ForceAreaTEST = QtWidgets.QMdiArea(self.centralwidget)
        self.ForceAreaTEST.setGeometry(QtCore.QRect(10, 80, 291, 161))
        self.ForceAreaTEST.setObjectName("ForceAreaTEST")
        self.openMainUI = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.open_window())
        self.openMainUI.setGeometry(QtCore.QRect(390, 0, 111, 41))
        self.openMainUI.setObjectName("openMainUI")
        self.VactualAreaTEST = QtWidgets.QMdiArea(self.centralwidget)
        self.VactualAreaTEST.setGeometry(QtCore.QRect(10, 280, 291, 161))
        self.VactualAreaTEST.setObjectName("VactualAreaTEST")
        self.forceblocktitleTEST = QtWidgets.QTextBrowser(self.centralwidget)
        self.forceblocktitleTEST.setGeometry(QtCore.QRect(10, 50, 291, 31))
        self.forceblocktitleTEST.setObjectName("forceblocktitleTEST")
        self.VactualblocktitleTEST = QtWidgets.QTextBrowser(self.centralwidget)
        self.VactualblocktitleTEST.setGeometry(QtCore.QRect(10, 250, 291, 31))
        self.VactualblocktitleTEST.setObjectName("VactualblocktitleTEST")
        self.AccelAreaTEST = QtWidgets.QMdiArea(self.centralwidget)
        self.AccelAreaTEST.setGeometry(QtCore.QRect(10, 480, 291, 161))
        self.AccelAreaTEST.setObjectName("AccelAreaTEST")
        self.AccelblocktitleTEST = QtWidgets.QTextBrowser(self.centralwidget)
        self.AccelblocktitleTEST.setGeometry(QtCore.QRect(10, 450, 291, 31))
        self.AccelblocktitleTEST.setObjectName("AccelblocktitleTEST")
        self.accelipBoxTEST = QtWidgets.QTextEdit(self.centralwidget)
        self.accelipBoxTEST.setEnabled(False)
        self.accelipBoxTEST.setGeometry(QtCore.QRect(20, 340, 101, 31))
        self.accelipBoxTEST.setObjectName("accelipBoxTEST")
        # self.VActualEditDoneTEST = QtWidgets.QPushButton(self.centralwidget)
        # self.VActualEditDoneTEST.setEnabled(True)
        # self.VActualEditDoneTEST.setGeometry(QtCore.QRect(80, 410, 41, 21))
        # self.VActualEditDoneTEST.setObjectName("VActualEditDoneTEST")
        self.VactualResultBoxTEST = QtWidgets.QTextEdit(self.centralwidget)
        self.VactualResultBoxTEST.setEnabled(False)
        self.VactualResultBoxTEST.setGeometry(QtCore.QRect(130, 310, 161, 121))
        self.VactualResultBoxTEST.setObjectName("VactualResultBoxTEST")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 320, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(130, 290, 121, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(130, 490, 151, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 490, 91, 16))
        self.label_9.setObjectName("label_9")
        self.forceipBoxTEST = QtWidgets.QTextEdit(self.centralwidget)
        self.forceipBoxTEST.setEnabled(False)
        self.forceipBoxTEST.setGeometry(QtCore.QRect(20, 510, 101, 31))
        self.forceipBoxTEST.setObjectName("forceipBoxTEST")
        # self.AccelEditDoneTEST = QtWidgets.QPushButton(self.centralwidget)
        # self.AccelEditDoneTEST.setEnabled(True)
        # self.AccelEditDoneTEST.setGeometry(QtCore.QRect(80, 610, 41, 21))
        # self.AccelEditDoneTEST.setObjectName("AccelEditDoneTEST")
        self.massipBoxTEST = QtWidgets.QTextEdit(self.centralwidget)
        self.massipBoxTEST.setEnabled(False)
        self.massipBoxTEST.setGeometry(QtCore.QRect(20, 570, 101, 31))
        self.massipBoxTEST.setObjectName("massipBoxTEST")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 550, 91, 16))
        self.label_10.setObjectName("label_10")
        self.accelResultBoxTEST = QtWidgets.QTextEdit(self.centralwidget)
        self.accelResultBoxTEST.setEnabled(False)
        self.accelResultBoxTEST.setGeometry(QtCore.QRect(130, 510, 161, 121))
        self.accelResultBoxTEST.setObjectName("accelResultBoxTEST")
        self.quickMetricsbaripTEST = QtWidgets.QComboBox(self.centralwidget)
        self.quickMetricsbaripTEST.setGeometry(QtCore.QRect(500, 0, 111, 41))
        self.quickMetricsbaripTEST.setObjectName("quickMetricsbaripTEST")
        self.ServiceBrakebutton_onTEST = QtWidgets.QCheckBox(
            self.centralwidget)
        self.ServiceBrakebutton_onTEST.setGeometry(
            QtCore.QRect(430, 290, 95, 20))
        self.ServiceBrakebutton_onTEST.setObjectName(
            "ServiceBrakebutton_onTEST")
        self.ServiceBrakeAreaTEST = QtWidgets.QMdiArea(self.centralwidget)
        self.ServiceBrakeAreaTEST.setGeometry(QtCore.QRect(310, 260, 181, 71))
        self.ServiceBrakeAreaTEST.setObjectName("ServiceBrakeAreaTEST")
        self.ControlsBoxTEST = QtWidgets.QTextBrowser(self.centralwidget)
        self.ControlsBoxTEST.setGeometry(QtCore.QRect(310, 230, 181, 31))
        self.ControlsBoxTEST.setObjectName("ControlsBoxTEST")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(320, 270, 101, 51))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.EbrakeAreaTEST = QtWidgets.QMdiArea(self.centralwidget)
        self.EbrakeAreaTEST.setGeometry(QtCore.QRect(310, 340, 181, 71))
        self.EbrakeAreaTEST.setObjectName("EbrakeAreaTEST")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(320, 350, 81, 51))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.Ebrakebutton_onTEST = QtWidgets.QCheckBox(self.centralwidget)
        self.Ebrakebutton_onTEST.setGeometry(QtCore.QRect(430, 360, 95, 20))
        self.Ebrakebutton_onTEST.setObjectName("Ebrakebutton_onTEST")
        self.LightsAreaTEST = QtWidgets.QMdiArea(self.centralwidget)
        self.LightsAreaTEST.setGeometry(QtCore.QRect(310, 420, 181, 71))
        self.LightsAreaTEST.setObjectName("LightsAreaTEST")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(320, 430, 91, 51))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.InternalLightsbutton_onTEST = QtWidgets.QCheckBox(
            self.centralwidget)
        self.InternalLightsbutton_onTEST.setGeometry(
            QtCore.QRect(430, 440, 95, 20))
        self.InternalLightsbutton_onTEST.setObjectName(
            "InternalLightsbutton_onTEST")
        self.RdoorAreaTEST = QtWidgets.QMdiArea(self.centralwidget)
        self.RdoorAreaTEST.setGeometry(QtCore.QRect(310, 580, 181, 91))
        self.RdoorAreaTEST.setObjectName("RdoorAreaTEST")
        self.Rdoorbutton_openTEST = QtWidgets.QCheckBox(self.centralwidget)
        self.Rdoorbutton_openTEST.setGeometry(QtCore.QRect(420, 610, 95, 20))
        self.Rdoorbutton_openTEST.setObjectName("Rdoorbutton_openTEST")
        self.LdoorAreaTEST = QtWidgets.QMdiArea(self.centralwidget)
        self.LdoorAreaTEST.setGeometry(QtCore.QRect(310, 680, 181, 91))
        self.LdoorAreaTEST.setObjectName("LdoorAreaTEST")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_10.setGeometry(QtCore.QRect(320, 690, 91, 71))
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.Ldoorbutton_openTEST = QtWidgets.QCheckBox(self.centralwidget)
        self.Ldoorbutton_openTEST.setGeometry(QtCore.QRect(420, 710, 95, 20))
        self.Ldoorbutton_openTEST.setObjectName("Ldoorbutton_openTEST")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_11.setGeometry(QtCore.QRect(310, 50, 181, 31))
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.StatusUpdateAreaTEST = QtWidgets.QMdiArea(self.centralwidget)
        self.StatusUpdateAreaTEST.setGeometry(QtCore.QRect(310, 80, 181, 141))
        self.StatusUpdateAreaTEST.setObjectName("StatusUpdateAreaTEST")
        self.powerFailBoxTEST = QtWidgets.QTextBrowser(self.centralwidget)
        self.powerFailBoxTEST.setGeometry(QtCore.QRect(320, 90, 131, 41))
        self.powerFailBoxTEST.setObjectName("powerFailBoxTEST")
        self.BrakeFailBoxTEST = QtWidgets.QTextBrowser(self.centralwidget)
        self.BrakeFailBoxTEST.setGeometry(QtCore.QRect(320, 130, 131, 41))
        self.BrakeFailBoxTEST.setObjectName("BrakeFailBoxTEST")
        self.SignalFailBoxTEST = QtWidgets.QTextBrowser(self.centralwidget)
        self.SignalFailBoxTEST.setGeometry(QtCore.QRect(320, 170, 131, 41))
        self.SignalFailBoxTEST.setObjectName("SignalFailBoxTEST")
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_15.setGeometry(QtCore.QRect(320, 590, 91, 71))
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(460, 180, 55, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(460, 140, 55, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(460, 100, 55, 16))
        self.label_14.setObjectName("label_14")
        self.LdoorAreaTEST_2 = QtWidgets.QMdiArea(self.centralwidget)
        self.LdoorAreaTEST_2.setGeometry(QtCore.QRect(160, 650, 141, 101))
        self.LdoorAreaTEST_2.setObjectName("LdoorAreaTEST_2")
        self.TempResultBoxTEST = QtWidgets.QTextEdit(self.centralwidget)
        self.TempResultBoxTEST.setEnabled(False)
        self.TempResultBoxTEST.setGeometry(QtCore.QRect(230, 660, 61, 51))
        self.TempResultBoxTEST.setObjectName("TempResultBoxTEST")
        self.tempControlip_TEST = QtWidgets.QSpinBox(self.centralwidget)
        self.tempControlip_TEST.setGeometry(QtCore.QRect(170, 690, 61, 21))
        self.tempControlip_TEST.setObjectName("tempControlip_TEST")
        self.TempEditSetTEST = QtWidgets.QPushButton(self.centralwidget)
        self.TempEditSetTEST.setGeometry(QtCore.QRect(180, 720, 31, 21))
        self.TempEditSetTEST.setObjectName("TempEditSetTEST")
        self.LdoorAreaTEST_3 = QtWidgets.QMdiArea(self.centralwidget)
        self.LdoorAreaTEST_3.setGeometry(QtCore.QRect(10, 680, 141, 111))
        self.LdoorAreaTEST_3.setObjectName("LdoorAreaTEST_3")
        self.BeaconblocktitleTEST = QtWidgets.QTextBrowser(self.centralwidget)
        self.BeaconblocktitleTEST.setGeometry(QtCore.QRect(10, 650, 141, 41))
        self.BeaconblocktitleTEST.setObjectName("BeaconblocktitleTEST")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_9.setGeometry(QtCore.QRect(170, 660, 71, 51))
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(270, 660, 55, 16))
        self.label_17.setObjectName("label_17")
        self.BeaconResultBoxTEST = QtWidgets.QTextBrowser(self.centralwidget)
        self.BeaconResultBoxTEST.setGeometry(QtCore.QRect(20, 730, 121, 51))
        self.BeaconResultBoxTEST.setObjectName("BeaconResultBoxTEST")
        self.QuickMetricsTitleBox_TEST = QtWidgets.QTextBrowser(
            self.centralwidget)
        self.QuickMetricsTitleBox_TEST.setGeometry(
            QtCore.QRect(500, 50, 111, 31))
        self.QuickMetricsTitleBox_TEST.setObjectName(
            "QuickMetricsTitleBox_TEST")
        self.GradeMetricsResultBoxTEST = QtWidgets.QTextBrowser(
            self.centralwidget)
        self.GradeMetricsResultBoxTEST.setGeometry(
            QtCore.QRect(500, 260, 111, 31))
        self.GradeMetricsResultBoxTEST.setObjectName(
            "GradeMetricsResultBoxTEST")
        self.SpeedLimitMetricsResultBoxTEST = QtWidgets.QTextBrowser(
            self.centralwidget)
        self.SpeedLimitMetricsResultBoxTEST.setGeometry(
            QtCore.QRect(500, 140, 111, 31))
        self.SpeedLimitMetricsResultBoxTEST.setObjectName(
            "SpeedLimitMetricsResultBoxTEST")
        self.AuthorityMetricsResultBoxTEST = QtWidgets.QTextBrowser(
            self.centralwidget)
        self.AuthorityMetricsResultBoxTEST.setGeometry(
            QtCore.QRect(500, 110, 111, 31))
        self.AuthorityMetricsResultBoxTEST.setObjectName(
            "AuthorityMetricsResultBoxTEST")
        self.ElevationMetricsResultBoxTEST = QtWidgets.QTextBrowser(
            self.centralwidget)
        self.ElevationMetricsResultBoxTEST.setGeometry(
            QtCore.QRect(500, 230, 111, 31))
        self.ElevationMetricsResultBoxTEST.setObjectName(
            "ElevationMetricsResultBoxTEST")
        self.DeccelLimitMetricsResultBoxTEST = QtWidgets.QTextBrowser(
            self.centralwidget)
        self.DeccelLimitMetricsResultBoxTEST.setGeometry(
            QtCore.QRect(500, 200, 111, 31))
        self.DeccelLimitMetricsResultBoxTEST.setObjectName(
            "DeccelLimitMetricsResultBoxTEST")
        self.AccelLimitMetricsResultBoxTEST = QtWidgets.QTextBrowser(
            self.centralwidget)
        self.AccelLimitMetricsResultBoxTEST.setGeometry(
            QtCore.QRect(500, 170, 111, 31))
        self.AccelLimitMetricsResultBoxTEST.setObjectName(
            "AccelLimitMetricsResultBoxTEST")
        self.TempMetricsResultBoxTEST = QtWidgets.QTextBrowser(
            self.centralwidget)
        self.TempMetricsResultBoxTEST.setGeometry(
            QtCore.QRect(500, 80, 111, 31))
        self.TempMetricsResultBoxTEST.setObjectName("TempMetricsResultBoxTEST")
        self.ServiceBrakeAreaTEST_2 = QtWidgets.QMdiArea(self.centralwidget)
        self.ServiceBrakeAreaTEST_2.setGeometry(
            QtCore.QRect(500, 340, 111, 71))
        self.ServiceBrakeAreaTEST_2.setObjectName("ServiceBrakeAreaTEST_2")
        self.ControlsBoxTEST_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.ControlsBoxTEST_2.setGeometry(QtCore.QRect(500, 320, 111, 31))
        self.ControlsBoxTEST_2.setObjectName("ControlsBoxTEST_2")
        self.SignalPickupFailure_TEST = QtWidgets.QCheckBox(self.centralwidget)
        self.SignalPickupFailure_TEST.setGeometry(
            QtCore.QRect(510, 350, 101, 20))
        self.SignalPickupFailure_TEST.setObjectName("SignalPickupFailure_TEST")
        self.ServiceBrakeFailure_TEST_2 = QtWidgets.QCheckBox(
            self.centralwidget)
        self.ServiceBrakeFailure_TEST_2.setGeometry(
            QtCore.QRect(510, 390, 101, 20))
        self.ServiceBrakeFailure_TEST_2.setObjectName(
            "ServiceBrakeFailure_TEST_2")
        self.eBrakeFailure_TEST = QtWidgets.QCheckBox(self.centralwidget)
        self.eBrakeFailure_TEST.setGeometry(QtCore.QRect(510, 370, 91, 20))
        self.eBrakeFailure_TEST.setObjectName("eBrakeFailure_TEST")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 180, 91, 16))
        self.label_11.setObjectName("label_11")
        self.VcmdipBoxTEST_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.VcmdipBoxTEST_2.setEnabled(True)
        self.VcmdipBoxTEST_2.setGeometry(QtCore.QRect(20, 200, 81, 31))
        self.VcmdipBoxTEST_2.setObjectName("VcmdipBoxTEST_2")
        self.BeaconipBoxTEST = QtWidgets.QComboBox(self.centralwidget)
        self.BeaconipBoxTEST.setGeometry(QtCore.QRect(20, 710, 121, 22))
        self.BeaconipBoxTEST.setObjectName("BeaconipBoxTEST")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 690, 101, 16))
        self.label_6.setObjectName("label_6")
        self.LightsAreaTEST_2 = QtWidgets.QMdiArea(self.centralwidget)
        self.LightsAreaTEST_2.setGeometry(QtCore.QRect(310, 500, 181, 71))
        self.LightsAreaTEST_2.setObjectName("LightsAreaTEST_2")
        self.ExtrernalLightsbutton_onTEST = QtWidgets.QCheckBox(
            self.centralwidget)
        self.ExtrernalLightsbutton_onTEST.setGeometry(
            QtCore.QRect(430, 520, 95, 20))
        self.ExtrernalLightsbutton_onTEST.setObjectName(
            "ExtrernalLightsbutton_onTEST")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_12.setGeometry(QtCore.QRect(320, 510, 91, 51))
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.ForceAreaTEST.raise_()
        self.poweripBoxTEST.raise_()
        self.label.raise_()
        self.TrainModelSimTitleTEST.raise_()
        self.CalculateButtonTEST.raise_()
        self.forceResultBoxTEST.raise_()
        self.VcmdipBoxTEST.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.openMainUI.raise_()
        self.VactualAreaTEST.raise_()
        self.forceblocktitleTEST.raise_()
        self.VactualblocktitleTEST.raise_()
        self.AccelAreaTEST.raise_()
        self.AccelblocktitleTEST.raise_()
        self.accelipBoxTEST.raise_()
        # self.VActualEditDoneTEST.raise_()
        self.VactualResultBoxTEST.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.forceipBoxTEST.raise_()
        # self.AccelEditDoneTEST.raise_()
        self.massipBoxTEST.raise_()
        self.label_10.raise_()
        self.accelResultBoxTEST.raise_()
        self.quickMetricsbaripTEST.raise_()
        self.ServiceBrakeAreaTEST.raise_()
        self.ControlsBoxTEST.raise_()
        self.ServiceBrakebutton_onTEST.raise_()
        self.textBrowser_6.raise_()
        self.EbrakeAreaTEST.raise_()
        self.textBrowser_7.raise_()
        self.Ebrakebutton_onTEST.raise_()
        self.LightsAreaTEST.raise_()
        self.textBrowser_8.raise_()
        self.InternalLightsbutton_onTEST.raise_()
        self.RdoorAreaTEST.raise_()
        self.Rdoorbutton_openTEST.raise_()
        self.LdoorAreaTEST.raise_()
        self.textBrowser_10.raise_()
        self.Ldoorbutton_openTEST.raise_()
        self.textBrowser_11.raise_()
        self.StatusUpdateAreaTEST.raise_()
        self.powerFailBoxTEST.raise_()
        self.BrakeFailBoxTEST.raise_()
        self.SignalFailBoxTEST.raise_()
        self.textBrowser_15.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.LdoorAreaTEST_2.raise_()
        self.TempEditSetTEST.raise_()
        self.BeaconblocktitleTEST.raise_()
        self.LdoorAreaTEST_3.raise_()
        self.textBrowser_9.raise_()
        self.tempControlip_TEST.raise_()
        self.BeaconResultBoxTEST.raise_()
        self.QuickMetricsTitleBox_TEST.raise_()
        self.GradeMetricsResultBoxTEST.raise_()
        self.SpeedLimitMetricsResultBoxTEST.raise_()
        self.AuthorityMetricsResultBoxTEST.raise_()
        self.ElevationMetricsResultBoxTEST.raise_()
        self.DeccelLimitMetricsResultBoxTEST.raise_()
        self.AccelLimitMetricsResultBoxTEST.raise_()
        self.TempMetricsResultBoxTEST.raise_()
        self.ServiceBrakeAreaTEST_2.raise_()
        self.ControlsBoxTEST_2.raise_()
        self.SignalPickupFailure_TEST.raise_()
        self.ServiceBrakeFailure_TEST_2.raise_()
        self.eBrakeFailure_TEST.raise_()
        self.label_11.raise_()
        self.VcmdipBoxTEST_2.raise_()
        self.BeaconipBoxTEST.raise_()
        self.label_6.raise_()
        self.TempResultBoxTEST.raise_()
        self.label_17.raise_()
        self.LightsAreaTEST_2.raise_()
        self.ExtrernalLightsbutton_onTEST.raise_()
        self.textBrowser_12.raise_()
        TestUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TestUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 26))
        self.menubar.setObjectName("menubar")
        self.menuOPen = QtWidgets.QMenu(self.menubar)
        self.menuOPen.setObjectName("menuOPen")
        TestUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TestUI)
        self.statusbar.setObjectName("statusbar")
        TestUI.setStatusBar(self.statusbar)
        self.actionMain_UI = QtWidgets.QAction(TestUI)
        self.actionMain_UI.setObjectName("actionMain_UI")
        self.menuOPen.addAction(self.actionMain_UI)
        self.menubar.addAction(self.menuOPen.menuAction())

        self.retranslateUi(TestUI)
        QtCore.QMetaObject.connectSlotsByName(TestUI)
        self._handler()

        # add items to beacon ip combo box
        self.BeaconipBoxTEST.addItem("Beacon")
        self.BeaconipBoxTEST.addItem("Beacon 1")
        self.BeaconipBoxTEST.addItem("Beacon 2")

        # NOTE: add items to the quick metrics bar
        self.quickMetricsbaripTEST.addItem("Select a Line")
        self.quickMetricsbaripTEST.addItem("Blue Line")
        self.quickMetricsbaripTEST.addItem("Red Line")
        self.quickMetricsbaripTEST.addItem("Green Line")

        # default values in the text boxes for the private variable
        # NOTE: finish setting default values for text boxes
        self.poweripBoxTEST.setText(str(self.trainModel.get_cmd_power()))
        self.VcmdipBoxTEST_2.setText(str(self.trainModel.get_passenger_mass()))
        self.forceResultBoxTEST.setText(str(self.trainModel.get_force()))
        self.forceipBoxTEST.setText(str(self.trainModel.get_force()))
        self.massipBoxTEST.setText(str(self.trainModel.get_passenger_mass()))
        self.accelResultBoxTEST.setText(str(self.trainModel.get_accel()))
        self.accelipBoxTEST.setText(str(self.trainModel.get_accel()))

        # see if the authority from track model gets posted
        self.AuthorityMetricsResultBoxTEST.setPlainText(str(self.trainModel.get_authority()))

        # TO DO: add functionality to the main UI (copy it over)
        # add update and handler functions and other stuff to post results

        # trigger for done buttons for calculations:
        # trigger function call when button is clicked
        self.CalculateButtonTEST.clicked.connect(self.Calculate)

        # trigger other key i/o
        # NOTE: add the controls radio buttons
        self.BeaconipBoxTEST.activated.connect(
            lambda: self.trainModel.set_beacon(str(self.BeaconipBoxTEST.currentText())))
        # trigger the temp control function
        self.TempEditSetTEST.clicked.connect(self.temp_control)
        self.quickMetricsbaripTEST.activated.connect(self.update_line_info)
        self.ServiceBrakebutton_onTEST.toggled.connect(
            lambda: self.trainModel.set_service_brake(self.ServiceBrakebutton_onTEST.isChecked()))
        self.Ebrakebutton_onTEST.toggled.connect(
            lambda: self.trainModel.set_e_brake(self.Ebrakebutton_onTEST.isChecked()))
        self.InternalLightsbutton_onTEST.toggled.connect(
            lambda: self.trainModel.set_internal_lights(self.InternalLightsbutton_onTEST.isChecked()))
        self.ExtrernalLightsbutton_onTEST.toggled.connect(
            lambda: self.trainModel.set_external_lights(self.ExtrernalLightsbutton_onTEST.isChecked()))
        self.Rdoorbutton_openTEST.toggled.connect(
            lambda: self.trainModel.set_right_doors(self.Rdoorbutton_openTEST.isChecked()))
        self.Ldoorbutton_openTEST.toggled.connect(
            lambda: self.trainModel.set_left_doors(self.Ldoorbutton_openTEST.isChecked()))

        # trigger faults:
        # NOTE: finish triggering for other fault modes
        self.SignalPickupFailure_TEST.toggled.connect(
            lambda: self.trainModel.set_signal_pickup_failure(self.SignalPickupFailure_TEST.isChecked()))
        self.eBrakeFailure_TEST.toggled.connect(
            lambda: self.trainModel.set_eBrake_failure(self.eBrakeFailure_TEST.isChecked()))
        self.ServiceBrakeFailure_TEST_2.toggled.connect(
            lambda: self.trainModel.set_service_brake_failure(self.ServiceBrakeFailure_TEST_2.isChecked()))

    # this function gets triggered whenever the done button is clicked
    def Calculate(self):
        # read input from text box in the test UI
        # read cmd power input from the train controller
        powerCmd = self.poweripBoxTEST.toPlainText()
        # send cmd power input to the set_cmd_power function
        self.trainModel.set_cmd_power(float(powerCmd))
        # read cmd velocity input from the train controller
        velocityCmd = self.VcmdipBoxTEST.toPlainText()
        # send cmd velocity input to the set_cmd_velocity function
        self.trainModel.set_cmd_velocity(float(velocityCmd))
        # read passenger mass input from the track model
        PassengerMass = self.VcmdipBoxTEST_2.toPlainText()
        # send passenger mass input to the set_passenger_mass function
        self.trainModel.set_passenger_mass(float(PassengerMass))
        # post to the other text boxes:
        # read input from the text box in the test UI
        force = self.forceResultBoxTEST.toPlainText()
        mass = self.VcmdipBoxTEST_2.toPlainText()
        # refresh set commands:
        self.trainModel.set_passenger_mass(float(mass))
        # display on test ui
        self.forceipBoxTEST.setText(str(force))  # refresh text box with force
        # refresh mass text box with passenger mass
        self.massipBoxTEST.setText(str(mass))
        # read input from text box
        accel = self.accelResultBoxTEST.toPlainText()
        self.trainModel.set_accel(float(accel))
        # refresh set commands:
        # refresh accel text box with calculated acceleration
        self.accelipBoxTEST.setText(str(accel))

    def temp_control(self):
        # read input from the spin box
        temp = self.tempControlip_TEST.value()
        self.trainModel.set_temperature(float(temp))

    def update_line_info(self):
        # change output for each line
        if self.quickMetricsbaripTEST.currentText() == "Blue Line":
            # write metrics to the test UI
            self.AuthorityMetricsResultBoxTEST.setPlainText(
                f"Authority: mi")  # need to get this input from somewhere
            self.SpeedLimitMetricsResultBoxTEST.setPlainText(
                f"Speed Limit: mph")  # need to get this input from somewhere
            self.AccelLimitMetricsResultBoxTEST.setPlainText(
                f"Accel Limit: mph")  # need to get this input from somewhere
            self.DeccelLimitMetricsResultBoxTEST.setPlainText(
                f"Decel Limit: mph")  # ASK about what 2/3 load means
            self.ElevationMetricsResultBoxTEST.setPlainText(
                f"Elevation: ft")  # need to get this input from somewhere
            self.GradeMetricsResultBoxTEST.setPlainText(
                f"Grade: ft")  # need to get this input from somewhere
            # write metrics to main UI
            try:
                self.ui.AuthorityMetricsResultBoxMAIN.setPlainText(
                    f"Authority: mi")  # send result to QuickMetricsResultBoxMAIN
                self.ui.SpeedLimitMetricsResultBoxMAIN.setPlainText(
                    f"Speed Limit: mph")  # send result to QuickMetricsResultBoxMAIN
                self.ui.AccelLimitMetricsResultBoxMAIN.setPlainText(
                    f"Accel Limit: mph")  # send result to QuickMetricsResultBoxMAIN
                self.ui.DeccelLimitMetricsResultBoxMAIN.setPlainText(
                    f"Decel Limit: mph")  # ASK about what 2/3 load means
                self.ui.ElevationMetricsResultBoxMAIN.setPlainText(
                    f"Elevation: ft")  # need to get this input from somewhere
                self.ui.GradeMetricsResultBoxMAIN.setPlainText(
                    f"Grade: ft")  # need to get this input from somewhere
            except AttributeError:
                print(
                    "Ui_MainUI object does not have an attribute 'QuickMetricsResultBoxMAIN'")
        # repeat conditions for red and green lines when needed

    # update function always gets called by handler function so that we continuously have updated values
    def update(self):
        _translate = QtCore.QCoreApplication.translate

        # print changed on train controller UI
        self.poweripBoxTEST.setPlainText(str(self.trainModel.get_cmd_power()))

        # update the test UI:
        self.BeaconResultBoxTEST.setText(str(self.trainModel.get_beacon()))
        self.TempResultBoxTEST.setPlainText(
            f"{str(self.trainModel.get_temperature())}°")
        self.TempMetricsResultBoxTEST.setPlainText(
            f"Temp:{str(self.trainModel.get_temperature())}°")
        self.forceResultBoxTEST.setText(str(self.trainModel.calc_Force()))
        self.accelResultBoxTEST.setText(
            str(self.trainModel.calc_acceleration()))
        # refresh actual velocity calculation in test UI
        self.VactualResultBoxTEST.setText(
            str(self.trainModel.calc_actual_velocity()))
        # update the main UI:
        try:
            self.ui.forceResultBoxMAIN.setText(
                str(round(self.trainModel.get_force(), 3)))
            self.ui.accelResultBoxMAIN.setText(
                str(round(self.trainModel.get_accel(), 3)))
            self.ui.VactualResultBoxMAIN.setText(
                str(round(self.trainModel.get_actual_velocity(), 3)))
            self.ui.BeaconResultBoxMAIN.setText(
                str(self.trainModel.get_beacon()))
            self.ui.TempMetricsResultBoxMAIN_2.setPlainText(
                f"Temp:{str(self.trainModel.get_temperature())}°")
            self.ui.serviceBrakeoutputMAIN.setPlainText(
                str(self.trainModel.get_service_brake()))
            self.ui.EbrakeoutputMAIN.setPlainText(
                str(self.trainModel.get_e_brake()))
            self.ui.LightoutputMAIN.setPlainText(
                str(self.trainModel.get_internal_lights()))
            self.ui.LightoutputMAIN_2.setPlainText(
                str(self.trainModel.get_external_lights()))
            self.ui.RdooroutputMAIN.setPlainText(
                str(self.trainModel.get_right_doors()))
            self.ui.LdooroutputMAIN.setPlainText(
                str(self.trainModel.get_left_doors()))
        except AttributeError:
            # print("cannot refresh attributes in main UI")
            print("")
        # check for failure modes
        self.check_power_failure()
        self.check_signal_failure()
        self.check_brake_failure()

    def _handler(self):
        self.timer = QTimer()
        self.timer.setInterval(100)  # refreshes every time period
        self.timer.timeout.connect(self.update)
        self.timer.start()

    # check for power failure:
    def check_power_failure(self):
        # if pCmd > Pmax
        if self.trainModel.get_cmd_power() > self.trainModel.Pmax:
            self.powerFailBoxTEST.setText(
                "Power/engine failure")  # display error message
            # refresh force result in the main UI:
            try:
                # refresh force calculation in test UI
                self.ui.powerFailBoxMAIN.setText("Power/engine failure")
            except AttributeError:
                print("")
        else:
            self.powerFailBoxTEST.setText(
                "power status: good")  # clear the error message
            try:
                # refresh force calculation in test UI
                self.ui.powerFailBoxMAIN.setText("power status: good")
            except AttributeError:
                print("")

    # check service brake failure:
    def check_signal_failure(self):
        if self.trainModel.get_signal_pickup_failure():
            self.SignalFailBoxTEST.setText(
                "Signal Pickup Failure")  # display error message
            # refresh force result in the main UI:
            try:
                self.ui.SignalFailBoxMAIN.setText(
                    "Signal Pickup Failure")  # refresh in main UI
            except AttributeError:
                print("")
        else:
            self.SignalFailBoxTEST.setText(
                "signal pick-up: good")  # clear error message
            # refresh force result in the main UI:
            try:
                self.ui.SignalFailBoxMAIN.setText(
                    "signal pick-up: good")  # refresh in main UI
            except AttributeError:
                print("")

    # check e-brake failure:
    def check_brake_failure(self):
        if self.trainModel.get_eBrake_failure():
            self.BrakeFailBoxTEST.setText("Emergency Brake Failure")
            try:
                self.ui.BrakeFailBoxMAIN.setText("Emergency Brake Failure")
            except AttributeError:
                print("")
        elif self.trainModel.get_service_brake_failure():
            self.BrakeFailBoxTEST.setText("Service Brake Failure")
            try:
                self.ui.BrakeFailBoxMAIN.setText("Service Brake Failure")
            except AttributeError:
                print("")
        else:
            self.BrakeFailBoxTEST.setText("Brake status: good")
            try:
                self.ui.BrakeFailBoxMAIN.setText("Brake status: good")
            except AttributeError:
                print("")

    def retranslateUi(self, TestUI):
        _translate = QtCore.QCoreApplication.translate
        TestUI.setWindowTitle(_translate("TestUI", "MainWindow"))
        self.poweripBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                               "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.CalculateButtonTEST.setText(_translate("TestUI", "Calculate"))
        self.TrainModelSimTitleTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                       "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                       "p, li { white-space: pre-wrap; }\n"
                                                       "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                       "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Train Model Simulator</span></p></body></html>"))
        self.forceResultBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                   "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                   "p, li { white-space: pre-wrap; }\n"
                                                   "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                   "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.VcmdipBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("TestUI", "Power Input:"))
        self.label_3.setText(_translate("TestUI", "Vcmd Input: "))
        self.label_4.setText(_translate("TestUI", "Calculated Force: "))
        self.openMainUI.setText(_translate("TestUI", "Open Main UI"))
        self.forceblocktitleTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                    "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                    "p, li { white-space: pre-wrap; }\n"
                                                    "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                    "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Force (Newtons) </span></p></body></html>"))
        self.VactualblocktitleTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                      "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                      "p, li { white-space: pre-wrap; }\n"
                                                      "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                      "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Actual Velocity (m/s)</span></p></body></html>"))
        self.AccelblocktitleTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                    "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                    "p, li { white-space: pre-wrap; }\n"
                                                    "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                    "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Acceleration (m/s</span><span style=\" font-size:10pt; vertical-align:super;\">2</span><span style=\" font-size:10pt;\">)</span></p></body></html>"))
        self.accelipBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                               "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        # self.VActualEditDoneTEST.setText(_translate("TestUI", "Done"))
        self.VactualResultBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                     "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                     "p, li { white-space: pre-wrap; }\n"
                                                     "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                     "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_5.setText(_translate("TestUI", "Acceleration Input:"))
        self.label_7.setText(_translate("TestUI", "Calculated velocity: "))
        self.label_8.setText(_translate("TestUI", "Calculated acceleration: "))
        self.label_9.setText(_translate("TestUI", "Force Input:"))
        self.forceipBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                               "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        # self.AccelEditDoneTEST.setText(_translate("TestUI", "Done"))
        self.massipBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_10.setText(_translate("TestUI", "Mass Input:"))
        self.accelResultBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                   "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                   "p, li { white-space: pre-wrap; }\n"
                                                   "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                   "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ServiceBrakebutton_onTEST.setText(_translate("TestUI", "ON"))
        self.ControlsBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; color:#0000ff;\">Controls🔧</span></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#0000ff;\">Service Brake </span><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">🚫</span></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600; color:#c80825;\">Emergency </span></p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600; color:#c80825;\">Brake </span><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">🛑</span></p></body></html>"))
        self.Ebrakebutton_onTEST.setText(_translate("TestUI", "ON"))
        self.textBrowser_8.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#0000ff;\">Internal </span></p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#0000ff;\">Lights</span><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">💡</span></p></body></html>"))
        self.InternalLightsbutton_onTEST.setText(_translate("TestUI", "ON"))
        self.Rdoorbutton_openTEST.setText(_translate("TestUI", "OPEN"))
        self.textBrowser_10.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">Left </span></p>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">Doors</span></p>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">🚪🚶🏻‍♂️</span></p></body></html>"))
        self.Ldoorbutton_openTEST.setText(_translate("TestUI", "OPEN"))
        self.textBrowser_11.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:9pt; font-weight:600;\">🚨</span><span style=\" font-size:9pt; font-weight:600; text-decoration: underline; color:#aa0000;\">Status Updates</span><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:9pt; font-weight:600;\">🚨</span></p></body></html>"))
        self.powerFailBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                 "p, li { white-space: pre-wrap; }\n"
                                                 "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                 "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.BrakeFailBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                 "p, li { white-space: pre-wrap; }\n"
                                                 "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                 "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.SignalFailBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                  "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                  "p, li { white-space: pre-wrap; }\n"
                                                  "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                  "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_15.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">Right </span></p>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">Doors</span></p>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">🚪🚶🏻‍♂️</span></p></body></html>"))
        self.label_12.setText(_translate("TestUI", "📶"))
        self.label_13.setText(_translate("TestUI", "🆘"))
        self.label_14.setText(_translate("TestUI", "⚠️"))
        self.TempResultBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                  "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                  "p, li { white-space: pre-wrap; }\n"
                                                  "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                  "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.TempEditSetTEST.setText(_translate("TestUI", "Set"))
        self.BeaconblocktitleTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                     "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                     "p, li { white-space: pre-wrap; }\n"
                                                     "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                     "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Beacon<span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">🚏</span></p></body></html>"))
        self.textBrowser_9.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:8pt; color:#cc8800;\">Temp</span></p>\n"
                                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI Emoji,sans-serif\'; font-size:8pt; color:#cc8800;\"><br /></p></body></html>"))
        self.label_17.setText(_translate("TestUI", "🌡️"))
        self.BeaconResultBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                    "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                    "p, li { white-space: pre-wrap; }\n"
                                                    "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                    "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.QuickMetricsTitleBox_TEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                          "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                          "p, li { white-space: pre-wrap; }\n"
                                                          "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                          "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600; color:#242424;\">Quick Metrics</span></p></body></html>"))
        self.GradeMetricsResultBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                          "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                          "p, li { white-space: pre-wrap; }\n"
                                                          "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                          "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.SpeedLimitMetricsResultBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                               "p, li { white-space: pre-wrap; }\n"
                                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                               "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.AuthorityMetricsResultBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                              "p, li { white-space: pre-wrap; }\n"
                                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ElevationMetricsResultBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                              "p, li { white-space: pre-wrap; }\n"
                                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.DeccelLimitMetricsResultBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                                "p, li { white-space: pre-wrap; }\n"
                                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                                "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.AccelLimitMetricsResultBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                               "p, li { white-space: pre-wrap; }\n"
                                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                               "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.TempMetricsResultBoxTEST.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                         "p, li { white-space: pre-wrap; }\n"
                                                         "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ControlsBoxTEST_2.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                  "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                  "p, li { white-space: pre-wrap; }\n"
                                                  "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                  "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; color:#aa0000;\">Failures</span></p></body></html>"))
        self.SignalPickupFailure_TEST.setText(
            _translate("TestUI", "Signal Fail"))
        self.ServiceBrakeFailure_TEST_2.setText(
            _translate("TestUI", "S-brake Fail"))
        self.eBrakeFailure_TEST.setText(_translate("TestUI", "E-brake Fail"))
        self.label_11.setText(_translate("TestUI", "Mass Input:"))
        self.VcmdipBoxTEST_2.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_6.setText(_translate("TestUI", "Select a Beacon"))
        self.ExtrernalLightsbutton_onTEST.setText(_translate("TestUI", "ON"))
        self.textBrowser_12.setHtml(_translate("TestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#0000ff;\">Extrernal </span></p>\n"
                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#0000ff;\">Lights</span><span style=\" font-family:\'Segoe UI Emoji,sans-serif\'; font-size:11pt;\">💡</span></p></body></html>"))
        self.menuOPen.setTitle(_translate("TestUI", "Open"))
        self.actionMain_UI.setText(_translate("TestUI", "Main UI"))


if __name__ == '__main__':
    import sys
    app = QApplication(sys.argv)
    test_ui = QtWidgets.QMainWindow()
    tm = TrainModel()
    # main = Ui_MainUI()
    ui = Ui_TestUI(tm)
    # ui_main = Ui_TestUI(main)
    ui.setupUi(test_ui)
    test_ui.show()
    sys.exit(app.exec_())
